### ISSUE TITLE
Visual improvement: Rotating loading icon not perfectly round (Upgrade screen)

### ISSUE THREAD

**Issue by te-online** [nextcloud/server#1248]
### Steps to reproduce
1. Upgrade your Nextcloud

### Expected behaviour
The new upgrade interface looks really nice! No more wall of text 😄 
However, the spinner shouldn't look like a ”buckled“ bike wheel.

### Actual behaviour
![spinner](https://cloud.githubusercontent.com/assets/4127167/18205851/84bbefde-7124-11e6-82b6-84edcccc3c1a.gif)

The problem is – in Chrome at least – a combination of multiple rounding and display problems.
For this particular situation the solution would be the following CSS instead of the current:

```CSS
.loading:after, .loading-small:after, .icon-loading:after, .icon-loading-dark:after, .icon-loading-small:after, .icon-loading-small-dark:after {
    z-index: 2;
    content: "";
    height: 33px; /* before: 32px */
    width: 33px; /* before: 32px */
    /* margin: -17px 0 0 -17px; */
    /* position: absolute; */
    display: block; /* to make this a not-inline-element */
    /* top: 50%; */
    /* left: 50%; */
    margin: auto; /* to center the circle */
    border-radius: 50%;
    -webkit-animation: rotate 8s infinite linear;
    animation: rotate .8s infinite linear;
    -webkit-transform-origin: center;
    -ms-transform-origin: center;
    transform-origin: center;
}
```

It leaves us with this look:
![spinner-correct](https://cloud.githubusercontent.com/assets/4127167/18206146/aaccfc58-7125-11e6-869f-be9a5345415a.gif)

The uneven number (33 instead of 32) helps the circle to be perfectly round (see http://stackoverflow.com/questions/24070899/border-radius-50-not-producing-perfect-circles-in-chrome) and the applied margin seems to add the most to the problem and is therefore eliminated in this solution.

I realize however, that this CSS probably wouldn't work in all situations where this icon is used. Maybe someone can come up with a more clever idea? If had one, I'd have a pull request ready 🙈
