### ISSUE TITLE
unable to download shared file 

### ISSUE THREAD

**Issue by praetorianguards** [nextcloud/server#13320]
### 

I am unable zo download a shared file 

see --> [https://imgur.com/a/uq51Mbl]

### Steps to reproduce
1. Install Nextcloud Docker and percona-server

```
`  docker_service:
           project_name: nextcloud
           definition:
             version: "{{ DOCER_COMPOSE_VERSION }}"
             services:
               db:
                 image: percona/percona-server:latest
                 container_name: "{{ CONTAINER_NAME_DB }}"
                 volumes:
                   - "{{ MOUNT_MYSQL }}:/etc/my.cnf.d/"
                   - "{{ MOUNT }}:{{ MOUNT }}"
                 environment:
                   - MYSQL_ROOT_PASSWORD={{ DB_PASSWORD }}
                   - MYSQL_PASSWORD={{ DB_PASSWORD }}
                   - MYSQL_DATABASE={{ DB_NAME }}
                   - MYSQL_USER={{ DB_USER }}
                   - MYSQL_HOST={{ DB_HOST }}


         

               app:
                 image: nextcloud
                 container_name: "{{ CONTAINER_NAME_APP }}"
                 links:
                   - "{{ DB_HOST }}"
                 ports:
                   - "{{ PORTS }}:80"
                 environment:
                   - APC_SHM_SIZE=128M
                   - OPCACHE_MEM_SIZE=128
                   - TZ=Europe/Berlin
                   - DB_TYPE=mysql
                   - NEXTCLOUD_ADMIN_USER={{ NEXTCLOUD_ADMIN_USER }}
                   - NEXTCLOUD_ADMIN_PASSWORD={{ NEXTCLOUD_ADMIN_PASSWORD }}
 
                   - MYSQL_ROOT_PASSWORD={{ DB_PASSWORD }}
                   - MYSQL_PASSWORD={{ DB_PASSWORD }}
                   - MYSQL_DATABASE={{ DB_NAME }}
                   - MYSQL_USER={{ DB_USER }}
                   - MYSQL_HOST={{ DB_HOST }}
                   - PHP_INI_SCAN_DIR"/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
                 volumes:
                   - "{{ MOUNT_NEXTCLOUD }}:/var/www/html"
                   - "{{ MOUNT_NEXTCLOUD }}data:/data"
                   - "{{ MOUNT_NEXTCLOUD }}config:/config"
                   - "{{ MOUNT_NEXTCLOUD }}apps:/apps2"
                   - "{{ MOUNT_NEXTCLOUD }}themes:/nextcloud/themes"
                   - "{{ MOUNT_NEXTCLOUD }}php-ini:/usr/local/etc/php/custom.d/"

`


```

2. Upload iso file and share with User or Group

### Expected behaviour
Be able to download File

### Actual behaviour
unable to Download file

### Server configuration
```

**Operating system*4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux*:

**Web server:*Digital ocean*

**Database:*5.7.24-26 Percona Server (GPL), Release 26, Revision c8fe767*

**PHP version:**

**Nextcloud version:*14.0.4* (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:*fresh*

**Where did you install Nextcloud from:*docker*

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

> No errors have been found.


 **List of activated apps:**
<details>
<summary>App list</summary>


> Enabled:
>   - accessibility: 1.0.1
>   - activity: 2.7.0
>   - cloud_federation_api: 0.0.1
>   - comments: 1.4.0
>   - dav: 1.6.0
>   - federatedfilesharing: 1.4.0
>   - federation: 1.4.0
>   - files: 1.9.0
>   - files_pdfviewer: 1.3.2
>   - files_sharing: 1.6.2
>   - files_texteditor: 2.6.0
>   - files_trashbin: 1.4.1
>   - files_versions: 1.7.1
>   - files_videoplayer: 1.3.0
>   - firstrunwizard: 2.3.0
>   - gallery: 18.1.0
>   - logreader: 2.0.0
>   - lookup_server_connector: 1.2.0
>   - nextcloud_announcements: 1.3.0
>   - notifications: 2.2.1
>   - oauth2: 1.2.1
>   - password_policy: 1.4.0
>   - provisioning_api: 1.4.0
>   - registration: 0.4.5
>   - serverinfo: 1.4.0
>   - sharebymail: 1.4.0
>   - support: 1.0.0
>   - survey_client: 1.2.0
>   - systemtags: 1.4.0
>   - theming: 1.5.0
>   - twofactor_backupcodes: 1.3.1
>   - updatenotification: 1.4.1
>   - workflowengine: 1.4.0
> Disabled:
>   - admin_audit
>   - encryption
>   - files_external
>   - user_external
>   - user_ldap
> 

**Nextcloud configuration:**
<details>
<summary>Config report</summary>


```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "xxx.xxx.xxx.xxx"
        ],
        "theme": "xxxxxxx",
        "default_language": "de",
        "default_locale": "DEFAULT_LANGUAGE",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "share_folder": "\/Shared",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "overwrite.cli.url": "https:\/\/dev.nextcloud.xxxxxx.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{imap.xxxxxx.de:993\/imap\/ssl}",
                    "xxxx.de"
                ]
            }
        ]
    }
}

```
**Are you using external storage, if yes which one:*local* 

**Are you using encryption:*no* 
**Are you using an external user-backend, if yes which one:*no* 

```
