### ISSUE TITLE
Invalid default avatar of new account with display name in Unicode

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13376]
NC 15.0.0
Firefox 64.0

### Steps to reproduce
1. Add user with display name in Unicode
2. Log in
3. Look at the avatar

![image](https://user-images.githubusercontent.com/9205230/50716581-411a7280-1093-11e9-9e0a-0355ffca8419.png)

**Comment by rullzer** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
I'm guessing our font does not support this, so we need a default font then?

**Comment by skjnldsv** [comment]
@R0maNNN After some tests, I can't reproduce. Do you have Chinese fonts installed on your machine?
You have imagick installed on php as well, correct?

**Comment by R0maNNN** [comment]
@skjnldsv it's a docker container.

docker-compose.yml (reduced):

```
version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  nextcloud:
  db:
```
