### ISSUE TITLE
Setup LDAP Backend not possible

### ISSUE THREAD

**Issue by thechonta** [nextcloud/server#16194]
Operating system:Ubuntu 18.04
**Web server: nginx/1.14.0 (Ubuntu)
**Database:mariadb Ver 15.1
**PHP version:(PostgreSQL) 10.9
**Nextcloud version:16.0.1
Server is an Migration from mariadb to postgresql and apache to nginx.

Bug is related to https://github.com/nextcloud/server/issues/3074
```bash
require_once($_SERVER['DOCUMENT_ROOT'].'/lib/base.php');
```
This is needed if you wanna configure LDAP Backend for the first time.
```bash
 sudo -u www-data php /var/www/nextcloud/occ app:check-code user_ldap
Deprecated file found: /var/www/nextcloud/apps/user_ldap/appinfo/update.php - please use repair steps
App is not compliant
```
Something i would not expect from an official app. but with the Line up it will work.
Probably you will not be affected if the LDAP Backend is setup in a previous version.

the nginx error file contains something like that.
```bash
thrown in /var/www/nextcloud/apps/user_ldap/ajax/getConfiguration.php on line 28" while reading response header from upstream, client: 192.168.1.221, server: testcloud.domain.de, request: "POST /apps/user_ldap/ajax/getConfiguration.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "testcloud.domain.de"
2019/07/02 12:41:07 [error] 13438#13438: *92 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC_JSON' not found in /var/www/nextcloud/apps/user_ldap/ajax/wizard.php:32
Stack trace:
#0 {main}
  thrown in /var/www/nextcloud/apps/user_ldap/ajax/wizard.php on line 32" while reading response header from upstream, client: 192.168.1.221, server: testcloud.domain.de, request: "POST /apps/user_ldap/ajax/wizard.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "testcloud.domain.de"
```

**Comment by kesselb** [comment]
cc @blizzz 

```
version: '3'

volumes:
  nextcloud:

services:
  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - ldap
    volumes:
      - nextcloud:/var/www/html
    restart: always

  ldap:
    image: rroemhild/test-openlda
```

Could not reproduce this issue with the above `docker-compose.yml`. Create a new nextcloud instance from scratch. Adding a new ldap backend works fine. Looks like some setup related issue.
