### ISSUE TITLE
Downloading files pauses then (sometimes ) times out

### ISSUE THREAD

**Issue by lukasradek** [nextcloud/server#16396]
### Steps to reproduce
1. Have bigger files (folder of files) stored on server (cloud), bigger = megabytes+
2. Download them via Android app "Synchronize", Windows App synchronization or web download

### Expected behaviour
File(s) should download.

### Actual behaviour
During the download after some time (seconds to minutes), the progress just stops and after waiting a bit (seconds to minutes) it either resumes, but most often just completely stops the download with following (depending on case):

- Windows app: Shows red X mark, with name of the current file and following messages: "Operation was cancelled", "Connection lost" and/or "Connection timeout". Those are my translations of the msgs originally in czech. After a while synchronization restarts and is able to resume, where it left of in case of a bigger file.

- Nextcloud Android app during synchonization of folder (of images, 5-18 MB each): Pushes notification "Download failed. Operation could not finish, server is not reachable" (again translated from cze) and moves on to the next file. Which usually gets stuck on 0% until it fails as well. Sometimes it download just fine. It is usually a streak of downloaded files, then bunch of failed (skipped) and so on.

- Web UI download: download fails and browser marks the download as failed

Just to be clear, I repeat, that in all cases it sometimes resumes the download without timing out.

### Further findings
I have tried downloading files from my server via http request successfully everytime with various file sizes from onboard sd card (asus tinker board) and from external HDD, which has the cloud data directory. Same goes for FTP transfers.
It seems to be more "time elapsed" based, than total filesize transfered based, because when downloading with higher download speed (3x), more data is able to go through in one resume-fail cycle.

php/7.3/apache2/php.ini (NOT cli/php.ini) has max exec time set to 10000, max file size to 16G, output buffering is off

### Server configuration

**Operating system**:
Debian
20180222-tinker-board-linaro-stretch-alip-v2.0.5
running on Asus Tinker Board

**Web server:**
Apache2 2.4.25

**Database:**
MariaDB
10.1.38-MariaDB-0+deb9u1 - Debian 9.8

**PHP version:**
7.3.7
7.3.7-1+0\~20190710.40+debian9~1.gbp032aec

**Nextcloud version:** (see Nextcloud admin page)
16.0.3 fresh install

**Where did you install Nextcloud from:**
manual download from nextcloud site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                                                                                                                                                                                                           
  - accessibility: 1.2.0                                                                                                                                                                                           
  - activity: 2.9.1                                                                                                                                                                                                
  - cloud_federation_api: 0.2.0                                                                                                                                                                                    
  - comments: 1.6.0                                                                                                                                                                                                
  - dav: 1.9.2                                                                                                                                                                                                     
  - federatedfilesharing: 1.6.0                                                                                                                                                                                    
  - federation: 1.6.0                                                                                                                                                                                              
  - files: 1.11.0                                                                                                                                                                                                  
  - files_pdfviewer: 1.5.0                                                                                                                                                                                         
  - files_rightclick: 0.13.0                                                                                                                                                                                       
  - files_sharing: 1.8.0                                                                                                                                                                                           
  - files_texteditor: 2.8.0                                                                                                                                                                                        
  - files_trashbin: 1.6.0                                                                                                                                                                                          
  - files_versions: 1.9.0                                                                                                                                                                                          
  - files_videoplayer: 1.5.0                                                                                                                                                                                       
  - firstrunwizard: 2.5.0                                                                                                                                                                                          
  - gallery: 18.3.0                                                                                                                                                                                                
  - logreader: 2.1.0                                                                                                                                                                                               
  - lookup_server_connector: 1.4.0                                                                                                                                                                                 
  - nextcloud_announcements: 1.5.0                                                                                                                                                                                 
  - notifications: 2.4.1                                                                                                                                                                                           
  - oauth2: 1.4.2                                                                                                                                                                                                  
  - password_policy: 1.6.0                                                                                                                                                                                         
  - privacy: 1.0.0                                                                                                                                                                                                 
  - provisioning_api: 1.6.0                                                                                                                                                                                        
  - recommendations: 0.4.0                                                                                                                                                                                         
  - serverinfo: 1.6.0                                                                                                                                                                                              
  - sharebymail: 1.6.0                                                                                                                                                                                             
  - support: 1.0.0                                                                                                                                                                                                 
  - survey_client: 1.4.0                                                                                                                                                                                           
  - systemtags: 1.6.0                                                                                                                                                                                              
  - theming: 1.7.0                                                                                                                                                                                                 
  - twofactor_backupcodes: 1.5.0                                                                                                                                                                                   
  - updatenotification: 1.6.0                                                                                                                                                                                      
  - viewer: 1.0.0                                                                                                                                                                                                  
  - workflowengine: 1.6.0                                                                                                                                                                                          
Disabled:                                                                                                                                                                                                          
  - admin_audit                                                                                                                                                                                                    
  - encryption                                                                                                                                                                                                     
  - files_external                                                                                                                                                                                                 
  - user_ldap   
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{                                                                                                                                                                                                                  
    "system": {                                                                                                                                                                                                    
        "instanceid": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                             
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                           
        "secret": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                 
        "trusted_domains": [                                                                                                                                                                                       
            "***MANUALLY REMOVED SENSITIVE VALUE***",                                                                                                                                                                                     
            "***MANUALLY REMOVED SENSITIVE VALUE***"                                                                                                                                                                                          
        ],                                                                                                                                                                                                         
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                          
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***/cloud",                                                                                                                                                    
        "dbtype": "mysql",                                                                                                                                                                                         
        "version": "16.0.3.0",                                                                                                                                                                                     
        "dbname": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                 
        "dbhost": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                 
        "dbport": "",                                                                                                                                                                                              
        "dbtableprefix": "oc_",                                                                                                                                                                                    
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                 
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                             
        "installed": true,                                                                                                                                                                                         
        "logfile": "\/var\/log\/nextcloud.log",                                                                                                                                                                    
        "filelocking.enabled": true,                                                                                                                                                                               
        "memcache.distributed": "\\OC\\Memcache\\Redis",                                                                                                                                                           
        "memcache.locking": "\\OC\\Memcache\\Redis",                                                                                                                                                               
        "redis": {                                                                                                                                                                                                 
            "host": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                               
            "port": 6379                                                                                                                                                                                           
        },                                                                                                                                                                                                         
        "updater.release.channel": "stable",                                                                                                                                                                       
        "maintenance": false,                                                                                                                                                                                      
        "theme": "",                                                                                                                                                                                               
        "loglevel": 0,                                                                                                                                                                                             
        "mysql.utf8mb4": true                                                                                                                                                                                      
    }                                                                                                                                                                                                              
}                    
```
</details>

**Are you using external storage, if yes which one:** Data directory is on external HDD, connected via usb

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome 75.0.3770.100 

**Operating system:**
Windows 10

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing logged during the issue.

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Nothing logged exactly during the issue, but occasionally I see:
Sabre\DAV\Exception\NotAuthenticated: No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

followed by mulitple:
Sabre\DAV\Exception\NotFound: File with name //Note3-sync could not be located

,which is not a folder included in the requested synchronization

{"reqId":"lGnauafs1z0VfnZg5rOh","level":0,"time":"2019-07-14T16:16:47+00:00","remoteAddr":"86.49.74.148","user":"--","app":"webdav","method":"PROPFIND","url":"\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/
","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misco
nfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is 
misconfigured","Code":0,"Trace":[{"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__cla
ss__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"autoR
equireLogin":true,"__class__":"Sabre\\DAV\\Auth\\Plugin"},"beforeMethod"],[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\HTTP\\Request"},{"__class_
_":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"abso
luteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/
lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"
Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/cloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/
var\/www\/cloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/cloud\/remote.php","line":163,"args":["\/var\/www\/cloud\/a
pps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":168,"CustomMessage":"--"},"userAgent":"OkHttp","version":"16.0.
3.0"}                                                                                                                                                                                                              
{"reqId":"rh5fgJHEkhO4Wdx7ptOf","level":0,"time":"2019-07-14T16:16:48+00:00","remoteAddr":"86.49.74.148","user":"lukas","app":"webdav","method":"PROPFIND","url":"\/cloud\/remote.php\/dav\/files\/lukas\/Note3-syn
c\/","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name \/\/Note3-sync could not be located","Code":0,"Trace":[{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php
","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["Note3-sync"]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":
"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/lukas\/Note3-sync"]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorF
orPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/lukas\/Note3-sync",["{DAV:}creationdate","{DAV:}displayname","{DAV:}getcontentlength","{DAV:}getcontenttype","{DAV:}getlastmodified","{DAV:}resour
cetype","{DAV:}source"],0]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"
Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\H
TTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\D
AV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\
/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\
/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"func
tion":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/radkovi.net\/cloud\/remote.php\/dav\/files\/lukas\/Note3-sync\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"S
abre\\HTTP\\Response"}]},{"file":"\/var\/www\/cloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/cloud\/apps\/dav\/appinfo\/v
2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/cloud\/remote.php","line":163,"args":["\/var\/www\/cloud\/apps\/dav\/appinfo\/v2\/remote.php"],"f
unction":"require_once"}],"File":"\/var\/www\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":234,"CustomMessage":"--"},"userAgent":"OkHttp","version":"16.0.3.0"}  

</details>
