### ISSUE TITLE
Index column size too large

### ISSUE THREAD

**Issue by markuman** [nextcloud/server#16448]
### Steps to reproduce
1. Using AWS Aurora 2 (Compatible to MySQL 5.7.12)
2. Update from Nextcloud 15 to Nextcloud 16

### Actual behaviour

In the DB Schema Update, the following sql statement

```sql
CREATE TABLE
	oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
	timestamp BIGINT UNSIGNED NOT NULL,
	started SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
	poll_token VARCHAR(255) NOT NULL,
	login_token VARCHAR(255) NOT NULL,
	public_key TEXT NOT NULL,
	private_key TEXT NOT NULL,
	client_name VARCHAR(255) NOT NULL,
	login_name VARCHAR(255) DEFAULT NULL,
	server VARCHAR(255) DEFAULT NULL,
	app_password VARCHAR(1024) DEFAULT NULL,
	UNIQUE INDEX poll_token (poll_token),
	UNIQUE INDEX login_token (login_token),
	INDEX timestamp (timestamp),
	PRIMARY KEY(id)) DEFAULT CHARACTER SET
	utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed;
```

produces the following error

```
SQL-Fehler [1709] [HY000]: Index column size too large. The maximum column size is 767 bytes.
```

In the past (we're running our nextcloud on aws aurora since nextcloud 13) I saw those error often. The trick was to dump the database into a native mysql or mariadb und start the update on that database. when it is finished, I simply dump the updated db and restore it on aurora.
That works fine until today when updating to nextcloud 16.

### Server configuration

* Docker Nextcloud Image 16.0.3
* AWS 5.7.mysql_aurora.2.04.3

**Nextcloud version:** (see Nextcloud admin page)

16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

Update from 15.0.10 to 16.0.3

**Where did you install Nextcloud from:**

Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

The SQL statement work when I removed the `ROW_FORMAT = compressed`.

Are there any disadvantages when the this table is not compressed? Any chance to change this on upstream so that nextcloud is still compatible with aws aurora?

**Comment by markuman** [comment]
I can handle the incompatiblity with proxysql 

```yml
    - name: nextcloud 16 fix
      proxysql_query_rules:
        login_user: "{{ proxy_sql_admin_user }}"
        login_password: "{{ proxy_sql_admin_password }}"
        match_digest: "CREATE.*"
        match_pattern: "ROW_FORMAT=compressed"
        replace_pattern: " "
        destination_hostgroup: "{{ hostgroup_master }}"
        active: 1
        retries: 3
        state: present
        load_to_runtime: True
```
*(_this is ansible syntax_)

AFAIU, the row compression benefits storage usage on cost of cpu usage. 

Any thought about other negative aspects which hit me hard on later updates?
