### ISSUE TITLE
Multiple share links for a folder seemingly share the same link

### ISSUE THREAD

**Issue by singinwhale** [nextcloud/server#16780]
### Steps to reproduce
1. Create an empty folder *foo*
2. Create a new share link for *foo*
3. Set that link's permissions to read only
4. Rename that link to *bar*
5. Add a second share link 
6. Set that second link's permissions to file-drop
7. Rename the second link to *rab*
8. Click the copy link button for both links and paste them somewhere

### Expected behaviour
When I click the copy link button I want to have the corresponding link in my clipboard
When I click on the context menu button I want to see the permissions set for that link
Bonus: I want to see which link is which without clicking on rename to see the placeholder name
### Actual behaviour
Both links end with *rab*
I only see the permissions for the *rab*-Link, the *bar*-Link has none of the radio-buttons marked
### Server configuration

**Operating system**:
Debian 9 
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
running the dockerhub "nextcloud" image
**Web server:**
Nginx running in nextcloud image
**Database:**
Mariadb running in nextcloud image
**PHP version:**
PHP 7.3.8 (cli)
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
N/A
**Where did you install Nextcloud from:**
using this docker-compose.yml file:
```
version: "3.6"

networks:
  databases:

volumes:
  nextcloud:
  mysql:

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - "9009:80"
    networks:
      - databases
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Z3Ae2Byx3XF51zLDwN
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
  redis:
    image: redis
    restart: always
    networks:
      - databases

  mariadb:
    image: mariadb
    restart: always
    networks:
      - databases
    environment:
      - "MYSQL_ROOT_PASSWORD=05HewrhiH8JOpCB6Sy"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_PASSWORD=Z3Ae2Byx3XF51zLDwN"
    volumes:
      - mysql:/var/lib/mysql
```
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                                    
  - accessibility: 1.2.0                    
  - activity: 2.9.1                         
  - bruteforcesettings: 1.4.0               
  - calendar: 1.7.0                         
  - checksum: 0.4.3                         
  - cloud_federation_api: 0.2.0             
  - comments: 1.6.0                         
  - dav: 1.9.2                              
  - deck: 0.6.6                             
  - drawio: 0.9.3                           
  - federatedfilesharing: 1.6.0             
  - federation: 1.6.0                       
  - files: 1.11.0                           
  - files_3d: 0.1.0                         
  - files_automatedtagging: 1.6.0           
  - files_fulltextsearch: 1.3.6             
  - files_markdown: 2.0.6                   
  - files_mindmap: 0.0.13                   
  - files_pdfviewer: 1.5.0                  
  - files_rightclick: 0.13.0                
  - files_sharing: 1.8.0                    
  - files_texteditor: 2.8.0                 
  - files_trashbin: 1.6.0                   
  - files_versions: 1.9.0                   
  - files_videoplayer: 1.5.0                
  - firstrunwizard: 2.5.0                   
  - flowupload: 0.1.2                       
  - fulltextsearch: 1.3.6                   
  - gallery: 18.3.0                         
  - impersonate: 1.3.0                      
  - logreader: 2.1.0                        
  - lookup_server_connector: 1.4.0          
  - mail: 0.15.2                            
  - nextcloud_announcements: 1.5.0          
  - notifications: 2.4.1                    
  - oauth2: 1.4.2                           
  - password_policy: 1.6.0                  
  - phonetrack: 0.5.2                       
  - privacy: 1.0.0                          
  - provisioning_api: 1.6.0                 
  - recommendations: 0.4.0                  
  - serverinfo: 1.6.0                       
  - sharebymail: 1.6.0                      
  - sharerenamer: 2.6.1                     
  - support: 1.0.0                          
  - survey_client: 1.4.0                    
  - systemtags: 1.6.0                       
  - theming: 1.7.0                          
  - twofactor_backupcodes: 1.5.0            
  - updatenotification: 1.6.0               
  - viewer: 1.1.0                           
  - workflowengine: 1.6.0                   
Disabled:                                   
  - admin_audit                             
  - encryption                              
  - files_external                          
  - user_ldap                               
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{                                                                           
    "system": {                                                             
        "memcache.local": "\\OC\\Memcache\\APCu",                           
        "apps_paths": [                                                     
            {                                                               
                "path": "\/var\/www\/html\/apps",                           
                "url": "\/apps",                                            
                "writable": false                                           
            },                                                              
            {                                                               
                "path": "\/var\/www\/html\/custom_apps",                    
                "url": "\/custom_apps",                                     
                "writable": true                                            
            }                                                               
        ],                                                                  
        "memcache.distributed": "\\OC\\Memcache\\Redis",                    
        "memcache.locking": "\\OC\\Memcache\\Redis",                        
        "redis": {                                                          
            "host": "***REMOVED SENSITIVE VALUE***",                        
            "port": 6379                                                    
        },                                                                  
        "instanceid": "***REMOVED SENSITIVE VALUE***",                      
        "overwritehost": "singinwhale.com",                                 
        "overwritewebroot": "\/cloud",                                      
        "overwriteprotocol": "https",                                       
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                    
        "secret": "***REMOVED SENSITIVE VALUE***",                          
        "trusted_domains": [                                                
            "singinwhale.com"                                               
        ],                                                                  
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                   
        "dbtype": "mysql",                                                  
        "version": "16.0.4.1",                                              
        "overwrite.cli.url": "http:\/\/singinwhale.com",                    
        "dbname": "***REMOVED SENSITIVE VALUE***",                          
        "dbhost": "***REMOVED SENSITIVE VALUE***",                          
        "dbport": "",                                                       
        "dbtableprefix": "",                                                
        "mysql.utf8mb4": true,                                              
        "dbuser": "***REMOVED SENSITIVE VALUE***",                          
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                      
        "installed": true,                                                  
        "loglevel": 2,                                                      
        "maintenance": false,                                               
        "mail_domain": "***REMOVED SENSITIVE VALUE***",                     
        "mail_smtpmode": "smtp",                                            
        "mail_sendmailmode": "smtp",                                        
        "mail_smtpauthtype": "LOGIN",                                       
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",               
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",                   
        "mail_smtpauth": 1,                                                 
        "mail_smtpport": "465",                                             
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",                   
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"                
    }                                                                       
}                                                                           
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
</details>

### Client configuration
**Browser:**
Vivaldi	2.6.1566.44 (Stable channel) (32-bit)
Revision	b104196d10e5b12a2690fe28e511909c2f4dcf4b
JavaScript	V8 7.5.288.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.102 Safari/537.36 Vivaldi/2.6.1566.44
Command Line	"C:\Program Files (x86)\Vivaldi\Application\vivaldi.exe" --flag-switches-begin --flag-switches-end --save-page-as-mhtml
Executable Path	C:\Program Files (x86)\Vivaldi\Application\vivaldi.exe
Profile Path	C:\Users\Manuel\AppData\Local\Vivaldi\User Data\Default
**Operating system:**
Windows 10 OS Version 1809 (Build 17763.678)
#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"UGa8yd07HPFfcrWBHBR5","level":3,"time":"2019-08-18T11:43:19+00:00","remoteAddr":"80.155.133.42","user":"singinwhale","app":"PHP","method":"POST","url":"\/cloud\/index.php\/apps\/sharerenamer\/rename","message":"Only variables should be passed by reference at \/var\/www\/html\/custom_apps\/sharerenamer\/db\/sharerenamermapper.php#30","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3835.0 Safari\/537.36","version":"16.0.4.1"}
```
</details>

#### Browser log
N/A
