### ISSUE TITLE
Text app integrity after update to Nextcloud 17

### ISSUE THREAD

**Issue by jookk** [nextcloud/server#16939]
### Steps to reproduce
1. upgrade from 16.04 to 17b3
2.
3.

### Expected behaviour
no verification errors
### Actual behaviour
Integrity check failed
### Server configuration

**Operating system**:
debian buster
**Web server:**
apache 2.3.8
**Database:**
mariadb
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
17b3
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.4
**Where did you install Nextcloud from:**
upgrade

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- text
	- EXTRA_FILE
		- .github/pull_request_template.md
		- .github/ISSUE_TEMPLATE/Bug_report.md
		- .github/ISSUE_TEMPLATE/Feature_request.md
		- package-lock.json
		- README.md
		- .tx/config
		- l10n/.gitkeep
		- .gitattributes
		- .l10nignore
		- .eslintrc.js
		- package.json

Raw output
==========
Array
(
    [text] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.github/pull_request_template.md] => Array
                        (
                            [expected] => 
                            [current] => 9307a7ab3b06266ccda57e66ae678b31db3faf26a51c508d60b9bc2874ed59d46bcd1c1d07970e2af0947f826f050f953cbf02a962a4b40cb1572f5fcd8f94a1
                        )

                    [.github/ISSUE_TEMPLATE/Bug_report.md] => Array
                        (
                            [expected] => 
                            [current] => 2a574514bba022a69c723616091bfd19eb5b4821aef95846eb942e90ee80cf2b2b8710091660fc99b43eb922b47d96f89b4e38c72d14909d76a9c88edbe7a28b
                        )

                    [.github/ISSUE_TEMPLATE/Feature_request.md] => Array
                        (
                            [expected] => 
                            [current] => 84541137d4035e61148e33f0560e8f96c2dffde247b672459cf45f32c57bcfb6a4479dcf9c45b6598e95f61369bfad2d16c7784d59a689ad46c7b332216f891b
                        )

                    [package-lock.json] => Array
                        (
                            [expected] => 
                            [current] => 851dfbb766522728bdb6b468b02e4f3bd8a5f481c1ce89c7d151764b8ec0c35344032d771b8bb94b3e99f6e625c580c41eb3e480166d165731039f6de2e002c4
                        )

                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => ec0ad73e49149bc6200d8b07cc14a6795936d6c150ad20d30c9d694ea6ebe4b4738f81fc50d1f84d68d0c62e045f1b854ab56a1264b9310aadb2aa54a7573194
                        )

                    [.tx/config] => Array
                        (
                            [expected] => 
                            [current] => 80dfc72f84d02213d63b236925f020fc21f17fc5d1964cd84c0530fb65f3738cd03ff923f50ba8396d5832f5a04276891733281ecba82321cb426f13aa968516
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                    [.gitattributes] => Array
                        (
                            [expected] => 
                            [current] => da176baa1edf0a8408ffa35e07849a980e68fe0dd5f53569e583aec2e362f61d47e1ff6968d2fd92787b59ee2f8f38cbe8dcdde7e3ef1e24081cd21dc61e1d30
                        )

                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 3a07b78d317a75ec5a027b869771b5464be4749f645e8e9e1999864c710ce5b115279bd159758addcf0bcd182e28da35da0156c5ff43af69bb869e5225818f98
                        )

                    [.eslintrc.js] => Array
                        (
                            [expected] => 
                            [current] => 74262fe75f2c990b21f1116e86083b5ec635a084a3c3cba8ef7cf62f6ea398ed5f1b94c770a230993273a7bd2ff1587106b778814331e4bf6c0e20b82340bc94
                        )

                    [package.json] => Array
                        (
                            [expected] => 
                            [current] => fec4073b810d23b3b314e58c1ba6c40f12f429fb623998685d65f93e5afc45f7ddc91d8467e905b00536c091ed3f5395b054f01df8d2f0dd6d213442d1241b11
                        )

                )

        )

**Comment by kesselb** [comment]
I don't see these files at https://download.nextcloud.com/server/prereleases/nextcloud-17.0.0beta3.zip. Mind to delete the files and check again if beta4 is out?

**Comment by jookk** [comment]
Yes. So I have to upgrade to b4 and delete theese files?

**Comment by kesselb** [comment]
Yes. First delete the files and than update to beta4 (there is no beta4 yet). I suppose these files were part of an earlier beta release.

**Comment by jookk** [comment]
And after that report?

Dňa 1. septembra 2019 9:24:06 odpoludnia používateľ Daniel Kesselberg 
<notifications@github.com> napísal:

**Comment by kesselb** [comment]
> And after that report?

That would be great :+1:

**Comment by juliushaertl** [comment]
This might be an issue with the text app being installed though the app store on 16 and updating to 17. Could you share your config.php? Do you use multiple app paths? What are the permissions of the apps/text/ directory?

**Comment by jookk** [comment]
I deleted thoose files. Now verification is ok except user policy and 
phonetrack, which I manually edited to fix

Yes, text app was installed on nc 16.
Only one app paths.
File permissions are 644 and folders 750 or 755
Dňa 2. septembra 2019 15:19:12 používateľ Julius Härtl 
<notifications@github.com> napísal:

**Comment by DidierLmn** [comment]
The same issue is present on the 17.0.0 release. 
Text app was also installed on nc 16, only 1 app path, and also 644 for files, and 750/755 for directories.

**Comment by juliushaertl** [comment]
Did you install the text app manually or though the app store? Are the files writable by your webserver (so the updater could remove them)?

**Comment by Wikinaut** [comment]
I upgraded from 16.0.5 to 17.0.0 and see these integrity warning. Should not happen, I guess.

```
- text
	- EXTRA_FILE
		- .github/pull_request_template.md
		- .github/ISSUE_TEMPLATE/Bug_report.md
		- .github/ISSUE_TEMPLATE/Feature_request.md
		- l10n/.gitkeep
		- .tx/config
		- package.json
		- README.md
		- .eslintrc.js
		- .gitattributes
		- .l10nignore
		- package-lock.json
```

**Comment by juliushaertl** [comment]
@Wikinaut Since you have the same result as the original bug report, can you check the following as well?

> Did you install the text app manually or though the app store? Are the files writable by your webserver (so the updater could remove them)?

**Comment by rco117** [comment]
same here as @Wikinaut reported.
Install though app store. Files are writeable by webserver user.

**Comment by dajiahao** [comment]
upgrade from latest 16 to 17.0.1 
same error messages appear even if I disable the text app and delete the app folder manually after enabling it again the same integrity warning comes back
text app was already installed on v16 via app store

**Comment by dajiahao** [comment]
did it again, now I only get these messages:
Results
=======
- text
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

doesn't matter if I delete the app folder and reinstall it

**Comment by dajiahao** [comment]
solution:
delete text app
download nextcloud17.0.1 archive and extract text app dir from there
rescan, all errors gone

**Comment by risturiz** [comment]
In my case deleted "text" app (logout/login) and reinstall text app from Nextcloud

**Comment by Obi-Wahn** [comment]
> solution:
> delete text app
> download nextcloud17.0.1 archive and extract text app dir from there
> rescan, all errors gone

I had the same problem and this was my way: deinstall the text app, delete the files via console and reinstall the text app via the store.

**Comment by Terrox** [comment]
> 
> 
> This might be an issue with the text app being installed though the app store on 16 and updating to 17. 

that is what I did.

**Comment by biva** [comment]
I confirm this error with an update from 16.0.4 to 17.0.1 :( I had installed text within Nextcloud on NC16

**Comment by Anagastes** [comment]
same here. Update from 16 to 17.

php occ app:remove text                                                                                                                                                                                          
text could not be removed as it is a shipped app

```
php occ integrity:check-app text                                                                                                                                                                                 - EXTRA_FILE:
    - .l10nignore:
      - expected: 
      - current: 3a07b78d317a75ec5a027b869771b5464be4749f645e8e9e1999864c710ce5b115279bd159758addcf0bcd182e28da35da0156c5ff43af69bb869e5225818f98
    - l10n/.gitkeep:
      - expected: 
      - current: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
    - package-lock.json:
      - expected: 
      - current: 851dfbb766522728bdb6b468b02e4f3bd8a5f481c1ce89c7d151764b8ec0c35344032d771b8bb94b3e99f6e625c580c41eb3e480166d165731039f6de2e002c4
    - .tx/config:
      - expected: 
      - current: 80dfc72f84d02213d63b236925f020fc21f17fc5d1964cd84c0530fb65f3738cd03ff923f50ba8396d5832f5a04276891733281ecba82321cb426f13aa968516
    - .gitattributes:
      - expected: 
      - current: da176baa1edf0a8408ffa35e07849a980e68fe0dd5f53569e583aec2e362f61d47e1ff6968d2fd92787b59ee2f8f38cbe8dcdde7e3ef1e24081cd21dc61e1d30
    - package.json:
      - expected: 
      - current: fec4073b810d23b3b314e58c1ba6c40f12f429fb623998685d65f93e5afc45f7ddc91d8467e905b00536c091ed3f5395b054f01df8d2f0dd6d213442d1241b11
    - .eslintrc.js:
      - expected: 
      - current: 74262fe75f2c990b21f1116e86083b5ec635a084a3c3cba8ef7cf62f6ea398ed5f1b94c770a230993273a7bd2ff1587106b778814331e4bf6c0e20b82340bc94
    - README.md:
      - expected: 
      - current: ec0ad73e49149bc6200d8b07cc14a6795936d6c150ad20d30c9d694ea6ebe4b4738f81fc50d1f84d68d0c62e045f1b854ab56a1264b9310aadb2aa54a7573194
    - .github/pull_request_template.md:
      - expected: 
      - current: 9307a7ab3b06266ccda57e66ae678b31db3faf26a51c508d60b9bc2874ed59d46bcd1c1d07970e2af0947f826f050f953cbf02a962a4b40cb1572f5fcd8f94a1
    - .github/ISSUE_TEMPLATE/Feature_request.md:
      - expected: 
      - current: 84541137d4035e61148e33f0560e8f96c2dffde247b672459cf45f32c57bcfb6a4479dcf9c45b6598e95f61369bfad2d16c7784d59a689ad46c7b332216f891b
    - .github/ISSUE_TEMPLATE/Bug_report.md:
      - expected: 
      - current: 2a574514bba022a69c723616091bfd19eb5b4821aef95846eb942e90ee80cf2b2b8710091660fc99b43eb922b47d96f89b4e38c72d14909d76a9c88edbe7a28b
```
