### ISSUE TITLE
Nextcloud server 16.0.4 installed from git returns 17.0.0.6

### ISSUE THREAD

**Issue by t2d** [nextcloud/server#17171]
### Steps to reproduce
1. Have a look at https://github.com/nextcloud/server/blob/v16.0.4/version.php#L32
or run
```
./occ status
  - installed: true
  - version: 17.0.0.6
  - versionstring: 17.0.0 Beta 4
  - edition: 
```

### Expected behaviour
It should return `array(16, 0, 4, 0)`

### Actual behaviour
It returns `array(17, 0, 0, 6)` and `17.0.0 Beta 4`

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
both

**Where did you install Nextcloud from:**
Git
