### ISSUE TITLE
Contacts and calendar app does not exist

### ISSUE THREAD

**Issue by zhang-wenchao** [nextcloud/server#17380]
The apps list is null.

Docker nextcloud:fpm-alpine 17.0.0

<img width="1914" alt="WX20191003-112230@2x" src="https://user-images.githubusercontent.com/5770157/66097278-4d0a7500-e5d0-11e9-83f0-1b1f82544c0a.png">

**Comment by zhang-wenchao** [comment]
Nextcloud log
```
"reqId":"CcsyXllxcGYTrOXg4Wha","level":3,"time":"2019-10-04T02:33:23+00:00","remoteAddr":"192.168.100.1","user":"chaochao","app":"index","method":"GET","url":"\/apps\/theming\/img\/core\/filetypes\/image.svg?v=0","message":{"Exception":"RuntimeException","Message":"Could not get appdata folder for theming","Code":0,"Trace":[{"file":"\/var\/www\/html\/lib\/private\/Files\/AppData\/AppData.php","line":155,"function":"getAppDataFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":[]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php","line":155,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["0"]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php","line":170,"function":"getCacheFolder","class":"OCA\\Theming\\ImageManager","type":"->","args":[]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/Controller\/IconController.php","line":87,"function":"getCachedImage","class":"OCA\\Theming\\ImageManager","type":"->","args":["icon-core-filetypes_image.svg"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes\/image.svg"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"app":"core","image":"filetypes\/image.svg","_route":"theming.Icon.getThemedIcon"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"app":"core","image":"filetypes\/image.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"app":"core","image":"filetypes\/image.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/theming\/img\/core\/filetypes\/image.svg"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/lib\/private\/Files\/AppData\/AppData.php","Line":116,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"17.0.0.9"}
```

**Comment by zhang-wenchao** [comment]
The new installation

**Comment by zhang-wenchao** [comment]
{
	"reqId": "CcsyXllxcGYTrOXg4Wha",
	"level": 3,
	"time": "2019-10-04T02:33:23+00:00",
	"remoteAddr": "192.168.100.1",
	"user": "chaochao",
	"app": "index",
	"method": "GET",
	"url": "\/apps\/theming\/img\/core\/filetypes\/image.svg?v=0",
	"message": {
		"Exception": "RuntimeException",
		"Message": "Could not get appdata folder for theming",
		"Code": 0,
		"Trace": [{
			"file": "\/var\/www\/html\/lib\/private\/Files\/AppData\/AppData.php",
			"line": 155,
			"function": "getAppDataFolder",
			"class": "OC\\Files\\AppData\\AppData",
			"type": "->",
			"args": []
		}, {
			"file": "\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php",
			"line": 155,
			"function": "newFolder",
			"class": "OC\\Files\\AppData\\AppData",
			"type": "->",
			"args": ["0"]
		}, {
			"file": "\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php",
			"line": 170,
			"function": "getCacheFolder",
			"class": "OCA\\Theming\\ImageManager",
			"type": "->",
			"args": []
		}, {
			"file": "\/var\/www\/html\/apps\/theming\/lib\/Controller\/IconController.php",
			"line": 87,
			"function": "getCachedImage",
			"class": "OCA\\Theming\\ImageManager",
			"type": "->",
			"args": ["icon-core-filetypes_image.svg"]
		}, {
			"file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
			"line": 170,
			"function": "getThemedIcon",
			"class": "OCA\\Theming\\Controller\\IconController",
			"type": "->",
			"args": ["core", "filetypes\/image.svg"]
		}, {
			"file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
			"line": 99,
			"function": "executeController",
			"class": "OC\\AppFramework\\Http\\Dispatcher",
			"type": "->",
			"args": [{
				"__class__": "OCA\\Theming\\Controller\\IconController"
			}, "getThemedIcon"]
		}, {
			"file": "\/var\/www\/html\/lib\/private\/AppFramework\/App.php",
			"line": 126,
			"function": "dispatch",
			"class": "OC\\AppFramework\\Http\\Dispatcher",
			"type": "->",
			"args": [{
				"__class__": "OCA\\Theming\\Controller\\IconController"
			}, "getThemedIcon"]
		}, {
			"file": "\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php",
			"line": 47,
			"function": "main",
			"class": "OC\\AppFramework\\App",
			"type": "::",
			"args": ["OCA\\Theming\\Controller\\IconController", "getThemedIcon", {
				"__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
			}, {
				"app": "core",
				"image": "filetypes\/image.svg",
				"_route": "theming.Icon.getThemedIcon"
			}]
		}, {
			"function": "__invoke",
			"class": "OC\\AppFramework\\Routing\\RouteActionHandler",
			"type": "->",
			"args": [{
				"app": "core",
				"image": "filetypes\/image.svg",
				"_route": "theming.Icon.getThemedIcon"
			}]
		}, {
			"file": "\/var\/www\/html\/lib\/private\/Route\/Router.php",
			"line": 297,
			"function": "call_user_func",
			"args": [{
				"__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
			}, {
				"app": "core",
				"image": "filetypes\/image.svg",
				"_route": "theming.Icon.getThemedIcon"
			}]
		}, {
			"file": "\/var\/www\/html\/lib\/base.php",
			"line": 1000,
			"function": "match",
			"class": "OC\\Route\\Router",
			"type": "->",
			"args": ["\/apps\/theming\/img\/core\/filetypes\/image.svg"]
		}, {
			"file": "\/var\/www\/html\/index.php",
			"line": 42,
			"function": "handleRequest",
			"class": "OC",
			"type": "::",
			"args": []
		}],
		"File": "\/var\/www\/html\/lib\/private\/Files\/AppData\/AppData.php",
		"Line": 116,
		"CustomMessage": "--"
	},
	"userAgent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36",
	"version": "17.0.0.9"
}

**Comment by zhang-wenchao** [comment]
Contacts and calendar app does not exist

**Comment by zhang-wenchao** [comment]
```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.14.2
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Comment by zhang-wenchao** [comment]
```
$ docker exec -u www-data -it nextcloud-app php occ app:install contacts
Error: Could not download app contacts
```

**Comment by zhang-wenchao** [comment]
docker-compose.yml
```
version: '3'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ~/docker/data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - db.env

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud-app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ~/docker/data/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TZ=Asia/Shanghai
      - http_proxy=http://192.168.100.53:1081
      - https_proxy=http://192.168.100.53:1081
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    container_name: nextcloud-web
    build: ./web
    restart: always
    volumes:
      - ~/docker/data/nextcloud/nextcloud:/var/www/html:ro
    ports:
      - "192.168.100.56:80:80"
      - "192.168.100.56:443:443"
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    container_name: nextcloud-cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ~/docker/data/nextcloud/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

networks:
  proxy-tier:
```
