### ISSUE TITLE
OCP\Lock\LockedException on first login

### ISSUE THREAD

**Issue by 9R** [nextcloud/server#17986]
### Steps to reproduce
1. Create new user
2. new user clicks on "Set password" link in welcome mail
3. new user tries to log in with new password

### Expected behaviour

delay first login atempt until all file locks during account creation are released

### Actual behaviour

4. confusing error message "error, token invalid" is displayed to user
5. error "OCP\Lock\LockedException: "Photos/Hummingbird.jpg" is locked" apears in log
6. if user tries to log in again a few seconds later, the Lock is resolved and everything works as expected 

### Server configuration

**Operating system**:
archlinux

**Web server:**
nginx 1.16.1

**Database:**
mariadb 10.4.10

**PHP version:**
7.3.11
**Nextcloud version:** (see Nextcloud admin page)
17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 16.0.6

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:              
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0 
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6                                        
  - cospend: 0.1.5                                         
  - dav: 1.13.0                                            
  - federatedfilesharing: 1.7.0      
  - federation: 1.7.0                                                                                                  
  - files: 1.12.0                                          
  - files_pdfviewer: 1.6.0                                 
  - files_rightclick: 0.15.1                               
  - files_sharing: 1.9.0                                   
  - files_trashbin: 1.7.0                                  
  - files_versions: 1.10.0                                                                                             
  - files_videoplayer: 1.6.0                               
  - firstrunwizard: 2.6.0                                                                                              
  - gallery: 18.4.0          
  - gpxpod: 4.1.0                                                                                                      
  - logreader: 2.2.0                                       
  - lookup_server_connector: 1.5.0                                                                                     
  - maps: 0.1.2                                            
  - music: 0.11.0                                                                                                      
  - news: 14.0.1                                           
  - nextcloud_announcements: 1.6.0                                                                                     
  - notes: 3.0.3           
  - notifications: 2.5.0                                                                                               
  - oauth2: 1.5.0                                          
  - password_policy: 1.7.0                                 
  - polls: 0.10.4                                          
  - privacy: 1.1.0
  - provisioning_api: 1.7.0                                
  - recommendations: 0.5.0                                 
  - richdocuments: 3.4.4                                   
  - serverinfo: 1.7.0                                      
  - sharebymail: 1.7.0                                     
  - socialsharing_email: 1.0.6 
  - spreed: 7.0.2                                          
  - support: 1.0.1                                         
  - survey_client: 1.5.0                                   
  - systemtags: 1.7.0                                      
  - tasks: 0.11.3                                                                                                      
  - text: 1.1.1                                                                                                        
  - theming: 1.8.0                                         
  - twofactor_admin: 1.0.0   
  - twofactor_backupcodes: 1.6.0                          
  - twofactor_nextcloud_notification: 2.1.1               
  - twofactor_totp: 4.0.0                                  
  - updatenotification: 1.7.0                             
  - viewer: 1.2.0                                          
  - workflowengine: 1.7.0                                  
Disabled:                    
  - admin_audit                                                                                                        
  - announcementcenter
  - dicomviewer         
  - encryption      
  - files_external  
  - jsloader                                               
  - ocsms          
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "version": "17.0.1.1",
        "installed": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "maintenance": false,
        "updater.release.channel": "stable",
        "default_language": "en",
        "defaultapp": "calendar,files,dashboard",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "share_folder": "\/Shared",
        "trusted_domains": [
            "nc.9-r.net",
            "oc.9-r.net"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "log_type": "file",
        "loglevel": 0,
        "log_rotate_size": 104857600,
        "forceSSLforSubdomains": true,
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "twofactor_rcdevsopenotp",
            "ocsms"
        ],
        "mail_sendmailmode": "smtp"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
tested with: Firefox, Chrome

**Operating system:**
Irrelevant, tested with: Archlinux, Android, Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
<IP address> - - [18/Nov/2019:13:15:58 +0100] "POST /login HTTP/1.1" 500 4675 "-" "Mozilla/5.0 (Linux; Android 9; Nokia 7.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"JvKLNdnZ5QlzNdL8FmwE","level":3,"time":"2019-11-18T12:15:58+00:00","remoteAddr":"195.226.179.34","user":"TestUserName","app":"index","method":"POST","url":"\/login","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"Photos\/Hummingbird.jpg\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":2050,"function":"lockPath","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg",1,false]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":1140,"function":"lockFile","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg",1]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":595,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_get_contents","\/TestUserName\/files\/Photos\/Hummingbird.jpg",["read"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/File.php","line":52,"function":"file_get_contents","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":447,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":391,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":278,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":83,"function":"safeAddPhoto","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***","TestUserName"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Hooks\/FileHooks.php","line":49,"function":"safeAddByFile","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\Maps\\Hooks\\{closure}","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/Hooks\/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Hooks\/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/Root.php","line":136,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/Node.php","line":109,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/File.php","line":109,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->","args":[["postWrite"]]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":473,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->","args":["w"]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":464,"function":"copyr","class":"OC_Util","type":"::","args":["\/var\/www\/nc\/core\/skeleton\/Photos",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":436,"function":"copyr","class":"OC_Util","type":"::","args":["\/var\/www\/nc\/core\/skeleton",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/User\/Session.php","line":533,"function":"copySkeleton","class":"OC_Util","type":"::","args":["TestUserName",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/User\/Session.php","line":391,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->","args":[true,true]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/CompleteLoginCommand.php","line":43,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\CompleteLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/LoggedInCheckCommand.php","line":50,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\LoggedInCheckCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/EmailLoginCommand.php","line":58,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\EmailLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/UidLoginCommand.php","line":54,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\UidLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/UserDisabledCheckCommand.php","line":57,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\UserDisabledCheckCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/PreLoginHookCommand.php","line":52,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/Chain.php","line":108,"function":"process","class":"OC\\Authentication\\Login\\PreLoginHookCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/core\/Controller\/LoginController.php","line":298,"function":"process","class":"OC\\Authentication\\Login\\Chain","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nc\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login"]},{"file":"\/var\/www\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nc\/lib\/private\/Files\/View.php","Line":1945,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/499421fefbd1aa2c23edce1cc5152b74\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/nc\/lib\/private\/Files\/Storage\/Common.php","line":743,"function":"acquireLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files\/499421fefbd1aa2c23edce1cc5152b74",1]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":593,"function":"acquireLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/Photos\/Hummingbird.jpg",1,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":593,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Photos\/Hummingbird.jpg",1,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":1940,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Photos\/Hummingbird.jpg",1,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":2050,"function":"lockPath","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg",1,false]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":1140,"function":"lockFile","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg",1]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/View.php","line":595,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_get_contents","\/TestUserName\/files\/Photos\/Hummingbird.jpg",["read"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/File.php","line":52,"function":"file_get_contents","class":"OC\\Files\\View","type":"->","args":["\/TestUserName\/files\/Photos\/Hummingbird.jpg"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":447,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":391,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":278,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Service\/PhotofilesService.php","line":83,"function":"safeAddPhoto","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***","TestUserName"]},{"file":"\/var\/www\/nc\/apps\/maps\/lib\/Hooks\/FileHooks.php","line":49,"function":"safeAddByFile","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\Maps\\Hooks\\{closure}","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/Hooks\/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Hooks\/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/Root.php","line":136,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/Node.php","line":109,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nc\/lib\/private\/Files\/Node\/File.php","line":109,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->","args":[["postWrite"]]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":473,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->","args":["w"]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":464,"function":"copyr","class":"OC_Util","type":"::","args":["\/var\/www\/nc\/core\/skeleton\/Photos",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/legacy\/util.php","line":436,"function":"copyr","class":"OC_Util","type":"::","args":["\/var\/www\/nc\/core\/skeleton",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/User\/Session.php","line":533,"function":"copySkeleton","class":"OC_Util","type":"::","args":["TestUserName",{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"\/var\/www\/nc\/lib\/private\/User\/Session.php","line":391,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->","args":[true,true]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/CompleteLoginCommand.php","line":43,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\CompleteLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/LoggedInCheckCommand.php","line":50,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\LoggedInCheckCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/EmailLoginCommand.php","line":58,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\EmailLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/UidLoginCommand.php","line":54,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\UidLoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/UserDisabledCheckCommand.php","line":57,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/ALoginCommand.php","line":39,"function":"process","class":"OC\\Authentication\\Login\\UserDisabledCheckCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/PreLoginHookCommand.php","line":52,"function":"processNextOrFinishSuccessfully","class":"OC\\Authentication\\Login\\ALoginCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/Authentication\/Login\/Chain.php","line":108,"function":"process","class":"OC\\Authentication\\Login\\PreLoginHookCommand","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/core\/Controller\/LoginController.php","line":298,"function":"process","class":"OC\\Authentication\\Login\\Chain","type":"->","args":[{"__class__":"OC\\Authentication\\Login\\LoginData"}]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"\/var\/www\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"\/var\/www\/nc\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login"]},{"file":"\/var\/www\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nc\/lib\/private\/Lock\/DBLockingProvider.php","Line":209},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Linux; Android 9; Nokia 7.1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/78.0.3904.96 Mobile Safari\/537.36","version":"17.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
none available.
```
</details>
