### ISSUE TITLE
Cannot get nextcloud running

### ISSUE THREAD

**Issue by mindrunner** [nextcloud/server#19055]
I am trying to set up a new naked nextcloud instance. Using this docker-compose script:

```
version: '3.7'

services:
  db:
    image: mariadb/server
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    expose:
      - 3306
    restart: always
    volumes:
      - /mnt/data/docker-data/nextcloud/mariadb:/var/lib/mysql
    networks: 
      - proxy-tier
    environment:
      - "MYSQL_PASSWORD=xxxxx"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_ROOT_PASSWORD=xxxxx"

  redis:
    image: redis:alpine
    restart: always
    networks: 
      - proxy-tier
       
  app:
    image: nextcloud:apache
    expose:
      - 80
    depends_on:
      - db
      - redis
    environment:
      - "MYSQL_HOST=db:3306"
      - "MYSQL_PASSWORD=xxxxx"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "NEXTCLOUD_TRUSTED_DOMAINS=nx.domain.com"
      - "NEXTCLOUD_ADMIN_USER=xxxxx"
      - "NEXTCLOUD_ADMIN_PASSWORD=xxxxx"
      - "REDIS_HOST=redis"
      - "VIRTUAL_HOST=nc.domain.com"
      - "VIRTUAL_PORT=80"
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "LETSENCRYPT_HOST=nc.domain.com"
      - "LETSENCRYPT_EMAIL=letsencrypt@domain.com"
    volumes:
      - /mnt/data/docker-data/nextcloud/data:/var/www/html
    networks: 
      - proxy-tier
    restart: always
 
  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /mnt/data/docker-data/nextcloud/data:/var/www/html
    entrypoint: /cron.sh
    networks: 
      - proxy-tier
    depends_on:
      - db
      - redis

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

I am getting the following error when creating the initial admin account:
`SQLSTATE[HY000] [2006] MySQL server has gone away`

### Steps to reproduce
1. docker-compose up -d
2. go to https://nc.domain.com
3. Try to create admin account

### Expected behaviour
Aadmin account created and logged in

### Actual behaviour
`SQLSTATE[HY000] [2006] MySQL server has gone away`
