### ISSUE TITLE
Error while adding apps

### ISSUE THREAD

**Issue by avendretter** [nextcloud/server#20942]
Hello there,

I am running a dockerized nextcloud+pg behind a traefik reverseproxy.

### Expected behaviour
normal activation of apps

### Actual behaviour

While activating apps like calendar or contacts my DB response with 
```
db_1   | 2020-05-12 14:34:59.494 UTC [56] ERROR:  more than one row returned by a subquery used as an expression
```
For more details, see DB error log section below.

### Server configuration

**Operating system:**
- Ubuntu 16.04 LTS
- Docker version 19.03.8, build afacb8b7f0

**Web server/Database/PHP version:**
<details>
<summary>my used docker-compose.yml file</summary>

```
version: '3.2'

networks:
  db_net:
  traefik_net:
    external: true

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    ports:
      - 5432:5432
    networks:
      - db_net

  app:
    image: nextcloud:apache
    restart: always
    hostname: nextcloud.mydomain
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.mydomain
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user
    networks:
      - traefik_net
      - db_net
    labels:
      - traefik.backend=nextcloud
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.rule=Host:nextcloud.mydomain
      - traefik.docker.network=traefik_net

volumes:
  db:
  nextcloud:

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username to this file
```
</details>

**Nextcloud/PHP/Pgsql version:** (see Nextcloud admin page)
<details>
<summary>Versions of Nextcloud/PHP/Pgsql</summary>

```
Version
Nextcloud 18.0.4

Ihre Version ist aktuell.Update-Kanal: Stabil 

PHP
Version: 7.3.17

Arbeitspeicher-Grenzwert: 512 MB

Maximale Ausführungszeit: 3600

Maximale Größe zum Hochladen: 2 MB

Datenbank
Art: pgsql

Version: PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

Größe: 72,5 MB
```
</details>

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install / deploy

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - calendar
  - contacts
  - documentserver_community
  - encryption
  - files_external
  - mail
  - onlyoffice
  - spreed
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.mydomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
nope

**Are you using encryption:** yes/no
nope

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
nope

#### DB server error log
<details>
<summary>DB server error log</summary>

```

db_1   | 2020-05-12 14:34:59.494 UTC [56] STATEMENT:  SELECT quote_ident(r.conname) as conname, pg_catalog.pg_get_constraintdef(r.oid, true) as condef
db_1   | 	                  FROM pg_catalog.pg_constraint r
db_1   | 	                  WHERE r.conrelid =
db_1   | 	                  (
db_1   | 	                      SELECT c.oid
db_1   | 	                      FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n
db_1   | 	                      WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'oc_migrations' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',user),' ','') from pg_catalog.pg_settings where name = 'search_path'),',')) AND n.oid = c.relnamespace
db_1   | 	                  )
db_1   | 	                  AND r.contype = 'f'
```
</details>
