### ISSUE TITLE
Can't share folder with external local storage

### ISSUE THREAD

**Issue by matchish** [nextcloud/server#21207]
# Steps to reproduce
Here is first part 
https://www.loom.com/share/7e45c4b4f27d4f97a4fed87c54c1c4c5
And second part directly related to the issue
https://www.loom.com/share/92ea594507a84e9b9fa2f4c85885f456

### Expected behaviour
We have to see `demoproject` folder in `demouser` account
### Actual behaviour
No `demoproject` folder in `demouser` account

### Server configuration
I've recorded demo using this docker-compose file
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.3
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:18.0.4-apache
    ports:
      - 8585:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
```
