### ISSUE TITLE
Unable to authenticate via desktop client login

### ISSUE THREAD

**Issue by jbtruffault** [nextcloud/server#23117]
1. I install nexctloud through docker-compose with this .yml:

```yaml
version: '2'

services:
  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="1"
      - MYSQL_PASSWORD=xxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - docker-bridge

  nextcloud_web:
    image: nextcloud
    container_name: nextcloud_web
    expose:
      - 80
    links:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
      - script:/home/scripts
    restart: unless-stopped
    environment:
      - TRUSTED_PROXIES=192.168.10.10
      - OVERWRITEHOST=cloud.oplgo.fr
      - OVERWRITEPROTOCOL=http
      - OVERWRITEWEBROOT=/
      - OVERWRITECONDADDR=192.168.10.10
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=xxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - docker-bridge

volumes:
  nextcloud: ~
  db: ~
  script: ~


networks:
  docker-bridge:
    external:
      name: br0
```

2. Once it's installed, I try to synchronise through the Windows client application 

3. I get this page

![image](https://user-images.githubusercontent.com/12747168/96600992-d54ddc00-12f1-11eb-8a34-a44baee56b68.png)

4. This error appears in the logs: 
```
[index] Error: Exception: Argument 1 passed to OC\Core\Controller\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "grantPage")
1. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "grantPage", OC\AppFramework\ ... {}, {_route: "core.C ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.C ... "})
3. /var/www/html/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "core.C ... "})
4. /var/www/html/lib/base.php line 1012
   OC\Route\Router->match("/login/v2/grant")
5. /var/www/html/index.php line 37
   OC::handleRequest()

GET /index.phpgrant
from 1.2.3.4 by user at 2020-09-30T16:06:42+00:00
```

At this point I cannot use the nextcloud client. As you see in my docker-compose.yml, I already tried to follow the steps written here https://github.com/nextcloud/server/issues/17303

Is it me or is it the code ? 

Regards
