### ISSUE TITLE
occ config:system:set should return a different output when unchanged

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24300]
### Steps

1. Run `occ config:system:set mail_smtpmode --value mail_smtpmode`
2. Run it again

### Expected result
An output with "Already set"

### Actual result
Exact same output.

### Version
Nextcloud 20.0.2

### Context
When using tools like Ansible, one might want to know whether a value was changed or not to be able to set the `changed_when` clause there based stdout result.

Also needs to be applied to the other occ config:*:set commands.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
I think this is rather a feature request

**Comment by nodiscc** [comment]
This is similar to https://github.com/nextcloud/server/issues/17789 (`'occ app:enable appname' should make it clear that an app was already enabled`) which was fixed some time ago.

Without this mechanism, configuration management tools like ansible are unable to tell what was actually changed or not. For example, I have this ansible task [[1]](https://github.com/nodiscc/xsrv/blob/master/roles/nextcloud/tasks/nextcloud.yml#L214):

```yaml
- name: set nextcloud config.php values (always returns changed)
  become: yes
  become_user: nextcloud
  command:
    cmd: /usr/bin/php ./occ config:system:set --type={{ item.type | default('string') }} {{ item.key }} --value={{ item.value }} # noqa no-changed-when
  args:
    chdir: "{{ nextcloud_install_dir }}/"
  with_items:
    - { key: "trusted_domains 1", value: "{{ nextcloud_fqdn }}" }
    - { key: "overwrite.cli.url", value: "{{ nextcloud_full_url }}" }
    - { key: "datadir", value: "{{ nextcloud_data_dir }}" }
    - { key: "dbtype", value: "{{ nextcloud_db_type }}" }
    - { key: "dbname", value: "{{ nextcloud_db_name }}" }
    - { key: "dbhost", value: "{{ nextcloud_db_host }}" }
    - { key: "dbuser", value: "{{ nextcloud_db_user }}" }
    - { key: "dbpassword", value: "{{ nextcloud_db_password }}", no_log: True }
    - { key: "logtimezone", value: "UTC" }
    - { key: "log_type", value: "file" }
    - { key: "log_authfailip", value: "true", type: "boolean" }
    - { key: "loglevel", value: "{{ nextcloud_loglevel }}", type: "integer" }
    - { key: "trashbin_retention_obligation", value: "auto" }
    - { key: "memcache.local", value: '\\OC\\Memcache\\APCu' }
    - { key: "share_folder", value: '{{ nextcloud_share_folder }}' }
    - { key: "defaultapp", value: "{{ nextcloud_defaultapp }}" }
    - { key: "upgrade.disable-web", value: "true", type: "boolean" }
    - { key: "simpleSignUpLink.shown", value: "false", type: "boolean" }
    - { key: "htaccess.rewritebase", value: "/" }
  no_log: "{{ item.no_log | default(False) }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: nextcloud-config
```

And the output is always the same (`changed`), regardless how many time this task gets applied:

```
TASK [nodiscc.xsrv.nextcloud : set nextcloud config.php values (always returns changed)] *****************************************************************************************
changed: [demo1.example.org] => (item={'key': 'trusted_domains 1', 'value': 'cloud.example.org'})
changed: [demo1.example.org] => (item={'key': 'overwrite.cli.url', 'value': 'https://cloud.example.org/'})
changed: [demo1.example.org] => (item={'key': 'datadir', 'value': '/var/nextcloud/data'})
changed: [demo1.example.org] => (item={'key': 'dbtype', 'value': 'pgsql'})
changed: [demo1.example.org] => (item={'key': 'dbname', 'value': 'nextcloud'})
changed: [demo1.example.org] => (item={'key': 'dbhost', 'value': 'localhost'})
changed: [demo1.example.org] => (item={'key': 'dbuser', 'value': 'nextcloud'})
changed: [demo1.example.org] => (item=None)
changed: [demo1.example.org] => (item={'key': 'logtimezone', 'value': 'UTC'})
changed: [demo1.example.org] => (item={'key': 'log_type', 'value': 'file'})
changed: [demo1.example.org] => (item={'key': 'log_authfailip', 'value': 'true', 'type': 'boolean'})
changed: [demo1.example.org] => (item={'key': 'loglevel', 'value': 1, 'type': 'integer'})
changed: [demo1.example.org] => (item={'key': 'trashbin_retention_obligation', 'value': 'auto'})
changed: [demo1.example.org] => (item={'key': 'memcache.local', 'value': '\\\\OC\\\\Memcache\\\\APCu'})
changed: [demo1.example.org] => (item={'key': 'share_folder', 'value': '/SHARED/'})
changed: [demo1.example.org] => (item={'key': 'defaultapp', 'value': 'files'})
changed: [demo1.example.org] => (item={'key': 'upgrade.disable-web', 'value': 'true', 'type': 'boolean'})
changed: [demo1.example.org] => (item={'key': 'simpleSignUpLink.shown', 'value': 'false', 'type': 'boolean'})
changed: [demo1.example.org] => (item={'key': 'htaccess.rewritebase', 'value': '/'})
changed: [demo1.example.org]

```

A fix would be highly appreciated.
