### ISSUE TITLE
SFTP External Storage error when executing "sudo -u www-data php occ files:scan --all", message: "App:core, Message:Can't get app storage, app files_external, user not logged in"

### ISSUE THREAD

**Issue by jstark-rozeos** [nextcloud/server#27490]
### Steps to reproduce
1.  Create External Storage connection, using SFTP
2.  Execute 'sudo -u www-data php occ files:scan --all' or 'sudo -u www-data php occ files:scan --path="[user]/files/[external_storage_mountpoint]"'

### Expected behaviour
Update Nextcloud with the contents of external storage location

### Actual behaviour
Logged error message: "App:core, Message:Can't get app storage, app files_external, user not logged in"

### Server configuration

**Operating system:**  Ubuntu 18.04

**Web server:**  nginx 1.17.5

**Database:**  MariaDB 10.3.20

**PHP version:**  7.3.27-9

**Nextcloud version:**:  20.0.10
**updated from an older Nextcloud**

**Where did you install Nextcloud from:**  download.nextcloud.com/server/releases/nextcloud-16.0.0.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
    accessibility: 1.6.0
    activity: 2.13.4
    admin_audit: 1.10.0
    bruteforcesettings: 2.1.0
    calendar: 2.2.2
    cloud_federation_api: 1.3.0
    comments: 1.10.0
    contacts: 3.5.1
    contactsinteraction: 1.1.0
    dashboard: 7.0.0
    dav: 1.16.2
    federatedfilesharing: 1.10.2
    federation: 1.10.1
    files: 1.15.0
    files_external: 1.11.1
    files_pdfviewer: 2.0.1
    files_rightclick: 0.17.0
    files_sharing: 1.12.2
    files_versions: 1.13.0
    files_videoplayer: 1.9.0
    groupfolders: 8.2.1
    logreader: 2.5.0
    lookup_server_connector: 1.8.0
    nextcloud_announcements: 1.9.0
    notifications: 2.8.0
    oauth2: 1.8.0
    password_policy: 1.10.1
    photos: 1.2.3
    privacy: 1.4.0
    provisioning_api: 1.10.0
    recommendations: 0.8.0
    serverinfo: 1.10.0
    settings: 1.2.0
    sharebymail: 1.10.0
    support: 1.3.0
    systemtags: 1.10.0
    text: 3.1.0
    theming: 1.11.0
    twofactor_backupcodes: 1.9.0
    updatenotification: 1.10.0
    user_status: 1.0.1
    viewer: 1.4.0
    weather_status: 1.0.0
    workflowengine: 2.2.0
Disabled:
    encryption
    files_trashbin
    firstrunwizard
    smb_test
    spreed
    survey_client
    user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "starkhome.org",
            "nextcloud.starkhome.org",
            "192.168.1.100"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.10.1",
        "overwrite.cli.url": "https:\/\/starkhome.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "America\/New_York",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:**  sftp

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:**  no

### Client configuration
**Browser:**  Firefox 89.0 64 bit

**Operating system:**  MacOS 10.14.6

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2021/06/12 12:27:56 [error] 8468#8468: r3.o.lencr.org could not be resolved (3: Host not found) while requesting certificate status, responder: r3.o.lencr.org, certificate: "/etc/letsencrypt/live/starkhome.org/fullchain.pem"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"UhC3GUBUGaRXmGzP9jMu","level":3,"time":"2021-06-12T12:28:29-04:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"20.0.10.1"}
{"reqId":"UhC3GUBUGaRXmGzP9jMu","level":3,"time":"2021-06-12T12:28:29-04:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"20.0.10.1"}
```
</details>
