### ISSUE TITLE
App names overlap again

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#27536]
![Bildschirmfoto von 2021-06-17 09-57-35](https://user-images.githubusercontent.com/213943/122355874-8d4f8980-cf52-11eb-84a7-4edc5b5bca15.png)

### Steps

* Have an app with a long name (or translation)
* If the app is active or hovered it will overlap the next entry causing readability issues (depending on language/font/appname)

cc @jancborchardt

**Comment by szaimen** [comment]
It is like this since https://github.com/nextcloud/server/pull/22924

**Comment by szaimen** [comment]
I'll just leave this here which fixes this if the appmenu doesn't have a gradient but I am not sure if it is the best fix to this problem:
```scss
#appmenu:hover li span {
    background-color: var(--color-primary);
    z-index: 3;
    border-radius: 10px;
}
#appmenu:hover li svg {
    z-index: 4;
}
```
