### ISSUE TITLE
Collabora Code Server is not working with NC since V.6.4.10.5

### ISSUE THREAD

**Issue by iPwnWolf** [nextcloud/server#28221]
After updating Collabora and trying to use it I recognized that it doesn't work anymore. I think this is not due to my configuration, rather a general bug.

Here is my docker-compose.yml:
```
services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./Container-Daten/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=******************
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./Container-Daten/html:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - VIRTUAL_HOST=cloud.secureserver.de
      - PHP_MEMORY_LIMIT=7G
      - HTTP_X_FORWARDED_HOST=cloud.secureserver.de
      - HTTP_X_FORWARDED_PROTO=https
      - TRUSTED_PROXIES=cloud.secureserver.de
    env_file:
      - db.env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./Container-Daten/html:/var/www/html
      - ./Container-Daten/html/cron.sh:/cron.sh:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  collab:
    image: collabora/code:6.4.10.4
    ports:
      - 9980:9980
    environment:
      - domain=cloud.secureserver.de
    restart: always
```

Only `image: collabora/code:6.4.10.4` works for me, not newer versions...
Anyone else having the same issue?
