### ISSUE TITLE
File extension name overlays the sharing icon on mobile

### ISSUE THREAD

**Issue by RDGAlmeida** [nextcloud/server#2905]
### File extension name overlays the sharing icon when is viewed on mobile with 320px width

The screenshot below is from Google Chrome inspector with 320px width 
![Alt Text](https://s23.postimg.org/nsy7d22dn/Screeshot_01.png)

## This issue can be solved changing the line 60 in mobile.css

I change the value from this:

``` css
@media only screen and (max-width: 768px) {
	table td.filename .nametext .innernametext {
	    max-width: 50%;
	}
}
```

To this:

``` css
@media only screen and (max-width: 768px) {
	table td.filename .nametext .innernametext {
	    max-width: calc(100% - 175px);
	}
}
```

## This is the result

![Alt text](https://s23.postimg.org/sqbry64cr/Screesho_02.png)

I hope you guys from Nextcloud can change that in the core, so I do not have to change this with each update
