### ISSUE TITLE
Profile page is not usable on mobile

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#29340]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open the profile with a mobile phone

### Expected behaviour
Looks at least okay

### Actual behaviour
![Bildschirmfoto am 2021-10-20 um 16 42 11](https://user-images.githubusercontent.com/213943/138115598-86a8d66c-160e-44b5-9a72-66305e1aac28.png)

**Comment by szaimen** [comment]
I've made it work with the following CSS:
```css
@media only screen and (max-width: 1000px) {
.profile__header {
height: 250px !important;
position: unset !important;
}
.profile__header__container {
grid-template-columns: unset !important;
}
.profile__header__container__displayname {
margin-top: 100px 20px 0px !important;
width: unset !important;
display: unset !important;
}
.profile__header__container__edit-button {
width: fit-content !important;
display: block !important;
margin: 30px auto !important;
}
.profile__content {
display: block !important;
}
.profile__blocks {
width: unset !important;
max-width: 600px !important;
margin: 0 auto !important;
padding: 20px 50px 50px 50px !important;
}
.profile__sidebar {
margin: unset !important;
}
}
```
