### ISSUE TITLE
Cannot change password, bad url called

### ISSUE THREAD

**Issue by andriusign** [nextcloud/server#30159]
I cannot reset my password, because all the requests by default go to HTTP instead of HTTPS. My cloud is setup to use HTTPS and Letsencrypt, and it all works, unless I want to change my pass. I click "Forgot password", get new email, open that email, navigate to https://example.com/lostpassword/reset/form/token123/username, enter my new pass and click "Reset password". 

Then the request goes to http://example.com/lostpassword/set/token123/username and fails instead of openning https url.

### Steps to reproduce
1. Click "Forgot password", get new email, open that email, navigate to https://example.com/lostpassword/reset/form/token123/username
2. Enter new password
3. Click change password

### Expected behaviour
password should have been changed

### Actual behaviour
request failed calling http instead of https url

Using latest Nextcloud Docker image https://hub.docker.com/_/nextcloud/

**Comment by andriusign** [comment]
@MorrisJobke @rullzer is anyone looking into this problem? It has paralyzed my own cloud...

**Comment by MorrisJobke** [comment]
> @MorrisJobke @rullzer is anyone looking into this problem? It has paralyzed my own cloud...

Both of us are not with the project full time anymore. But maybe @skjnldsv can help here.

**Comment by andriusign** [comment]
@skjnldsv can you help please? This is really important issue that breaks using Nextcloud in general. It is not usable at all without password reset working properly.

**Comment by skjnldsv** [comment]
> Then the request goes to http://example.com/lostpassword/set/token123/username and fails instead of openning https url.

Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by andriusign** [comment]
Here you go:
First of all, wrong email link is sent, is should be HTTPS since LetsEncrypt is used.
![wrong-email-link](https://user-images.githubusercontent.com/14263959/146939701-19e9ed47-4592-4c7a-a9cf-e49e9d814147.png)

Then after navigating to password change url, I am redirected to HTTPS (looks like Nginx is doing its job)
![initial-load](https://user-images.githubusercontent.com/14263959/146939909-e4edcdc2-6204-4517-a033-1c4053ad524f.png)

And finally after submitting I see that request is sent to wrong URL. It should be HTTPS, since Nginx already done its job and forwarded us to secure page, I believe there is a misconfig in URL formatting, or absoulute path being used. It should just be /lostpassword/set/token21313 and then I believe it would work. However this is not a solution, but a workaround. The real problem should be fixed at the core.
![after](https://user-images.githubusercontent.com/14263959/146940186-027b1897-9846-4a41-815b-5b7cad2cce01.png)

**Comment by szaimen** [comment]
@andriusign can you please also share your config.php? We need it for debugging. Thanks!

**Comment by andriusign** [comment]
docker-compose.yml
```
version: '3'

services:
  # dns:
  #   image: phensley/docker-dns
  #   hostname: cloud
  #   domainname: cloud.example.com
  #   volumes:
  #     - /var/run/docker.sock:/docker.sock

  proxy:
    # image: jwilder/nginx-proxy:alpine
    build: ./proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    # depends_on:
    #   - dns
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    environment:
      - DEFAULT_EMAIL=user@example.com
    volumes:
      - acme:/etc/acme.sh
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: nextcloud-db
    networks:
      - nextcloud_network
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud_network
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
      - redis
    volumes:
      - ./nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=cloud.example.com
      - LETSENCRYPT_HOST=cloud.example.com
      - LETSENCRYPT_EMAIL=user@example.com
      - REDIS_HOST=redis
    # env_file:
    #   - db.env
    restart: unless-stopped

volumes:
  nextcloud:
  db:
  acme:

networks:
  nextcloud_network:

```

I have not change config.php from the inside of the container, but here you are:
```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'password' => '',
    'port' => 6379,
  ),
  'instanceid' => ''********************',',
  'passwordsalt' => '********************',
  'secret' => ''********************',',
  'trusted_domains' => 
  array (
    0 => 'cloud.example.com',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '22.1.1.2',
  'overwrite.cli.url' => 'https://cloud.example.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_user',
  'dbpassword' => '**************',
  'installed' => true,
  'mail_from_address' => 'mailer',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'example.com',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'mail.example.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'mailer@example.com',
  'mail_smtppassword' => '***************',
  'mail_smtpport' => '587',
);

```
