### ISSUE TITLE
cron.sh => 0 cron job done

### ISSUE THREAD

**Issue by JMLX42** [nextcloud/server#30513]
### Steps to reproduce

1. Use `/cron.sh` as documented [here](https://github.com/nextcloud/docker/blob/c046638a989032c3fbea02b40b5af8fc1eb3c9d7/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml#L39)

### Expected behaviour

Cron jobs are expected to be executed.

### Actual behaviour

0 cron jobs are ran: `select count(*) from jobs;` always returns the same value.

### Workaround

Running `cron.php` manually in the `app` container works as expected:

```bash
docker-compose -f /srv/nextcloud/docker-compose.yml exec -u www-data app php -f cron.php
```

### Server configuration

```yml
version: '3'

services:
  app:
    image: nextcloud:23.0.0
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - /mnt/nextcloud/html:/var/www/html
      - /mnt/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/nextcloud/config:/var/www/html/config
      - /mnt/nextcloud/data:/var/www/html/data
    networks:
      - server
      - nginx-proxy_reverse-proxy
    environment:
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "<secret>"
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.example.com app"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "<secret>"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      REDIS_HOST: "redis"
      VIRTUAL_HOST: "cloud.example.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "cloud.example.com"
      APACHE_DISABLE_REWRITE_IP: "1"
  cron:
    image: nextcloud:23.0.0
    restart: unless-stopped
    volumes:
      - /mnt/nextcloud/html:/var/www/html
      - /mnt/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/nextcloud/config:/var/www/html/config
      - /mnt/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - server
  db:
    image: "mariadb:10.5.11"
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "<secret>"
      MARIADB_PASSWORD: "<secret>"
      MARIADB_DATABASE: "nextcloud"
      MARIADB_USER: "nextcloud"
    volumes:
      - '/mnt/nextcloud/database:/var/lib/mysql'
    networks:
      - server
  redis:
    image: "redis:6.2.4"
    restart: unless-stopped
    networks:
      - server
    volumes:
      - "/mnt/nextcloud/cache:/data"
  onlyoffice-document-server:
    image: onlyoffice/documentserver:6.4.2
    restart: unless-stopped
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - server
      - nginx-proxy_reverse-proxy
    environment:
      VIRTUAL_HOST: "document.cloud.example.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "document.cloud.example.com"
```

**Operating system:** Debian (Docker)

**Web server:** Apache2

**Database:** MariaDB 10.5.11

**PHP version:** 8

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 22.0

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.5
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.2.1
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - calendar
  - circles
  - contactsinteraction
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - user_ldap
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

```
</details>

**Are you using external storage, if yes which one:** local storage but it's a goofys partition

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration

N/A

### Logs

```
cron_1                        | crond: crond (busybox 1.30.1) started, log level 0
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: wakeup dt=6
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond:  job: 0 php -f /var/www/html/cron.php
cron_1                        | crond: child running /bin/bash
cron_1                        | crond: USER www-data pid   8 cmd php -f /var/www/html/cron.php
cron_1                        | PHP Notice:  fwrite(): Write of 3333 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | Exception: Not installed in /var/www/html/lib/base.php:277
cron_1                        | Stack trace:
cron_1                        | #0 /var/www/html/lib/base.php(649): OC::checkInstalled(Object(OC\SystemConfig))
cron_1                        | #1 /var/www/html/lib/base.php(1087): OC::init()
cron_1                        | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron_1                        | #3 {main}
cron_1                        | PHP Notice:  fwrite(): Write of 2306 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | crond: wakeup dt=10
cron_1                        | crond: wakeup dt=50
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond:  job: 0 php -f /var/www/html/cron.php
cron_1                        | crond: child running /bin/bash
cron_1                        | crond: USER www-data pid   9 cmd php -f /var/www/html/cron.php
cron_1                        | PHP Notice:  fwrite(): Write of 3333 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | Exception: Not installed in /var/www/html/lib/base.php:277
cron_1                        | Stack trace:
cron_1                        | #0 /var/www/html/lib/base.php(649): OC::checkInstalled(Object(OC\SystemConfig))
cron_1                        | #1 /var/www/html/lib/base.php(1087): OC::init()
cron_1                        | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron_1                        | #3 {main}
cron_1                        | PHP Notice:  fwrite(): Write of 2306 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | crond: wakeup dt=10
cron_1                        | crond: wakeup dt=50
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond:  job: 0 php -f /var/www/html/cron.php
cron_1                        | crond: child running /bin/bash
cron_1                        | crond: USER www-data pid  10 cmd php -f /var/www/html/cron.php
cron_1                        | PHP Notice:  fwrite(): Write of 3333 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | Exception: Not installed in /var/www/html/lib/base.php:277
cron_1                        | Stack trace:
cron_1                        | #0 /var/www/html/lib/base.php(649): OC::checkInstalled(Object(OC\SystemConfig))
cron_1                        | #1 /var/www/html/lib/base.php(1087): OC::init()
cron_1                        | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron_1                        | #3 {main}
cron_1                        | PHP Notice:  fwrite(): Write of 2306 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | crond: wakeup dt=10
cron_1                        | crond: crond (busybox 1.30.1) started, log level 0
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: wakeup dt=37
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: crond (busybox 1.30.1) started, log level 0
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: user:www-data entry:(null)
cron_1                        | 100001000010000100001000010000100001000010000100001000010000
cron_1                        | 111111111111111111111111
cron_1                        | 11111111111111111111111111111111
cron_1                        | 111111111111
cron_1                        | 1111111
cron_1                        | crond: wakeup dt=58
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond: wakeup dt=60
cron_1                        | crond: file www-data:
cron_1                        | crond:  line php -f /var/www/html/cron.php
cron_1                        | crond:  job: 0 php -f /var/www/html/cron.php
cron_1                        | crond: child running /bin/bash
cron_1                        | crond: USER www-data pid   8 cmd php -f /var/www/html/cron.php
cron_1                        | PHP Notice:  fwrite(): Write of 3333 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | Exception: Not installed in /var/www/html/lib/base.php:277
cron_1                        | Stack trace:
cron_1                        | #0 /var/www/html/lib/base.php(649): OC::checkInstalled(Object(OC\SystemConfig))
cron_1                        | #1 /var/www/html/lib/base.php(1087): OC::init()
cron_1                        | #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
cron_1                        | #3 {main}
cron_1                        | PHP Notice:  fwrite(): Write of 2306 bytes failed with errno=95 Operation not supported in /var/www/html/lib/private/Log/File.php on line 89
cron_1                        | crond: wakeup dt=10
```

#### Web server error log

N/A

#### Nextcloud log (data/nextcloud.log)

Nothing relevant AFAIK.

#### Browser log

N/A
