### ISSUE TITLE
Separate user data from application data in data directory

### ISSUE THREAD

**Issue by k-svn** [nextcloud/server#32270]
I would like to separate user data from application data in the data directory. The goal is to store only the user files on a nfs share. If I change the path of the data directory in config.php to the share, there is also application data like appstore_<Instance-ID> and updater-<Instance-ID>.

Can't the several user directories be created in another subfolder "users"? This folder can then be relocated with a symlink.

Maybe there is already a possibility?

**Comment by bdrewery** [comment]
A symlink or nullfs/bind mount does not work on the appdata dir?

**Comment by solracsf** [comment]
See also https://github.com/nextcloud/server/issues/12873

**Comment by k-svn** [comment]
Say, we relocate data directory to a nfs share. Then you have a lot to link back to local file system, because we want only user data on the share:

├── appdata_XYZ  (relocate via symlink)
├── audit.log (relocate via symlink)
├── index.html (relocate via symlink)
├── **user1**
├── **user2**
├── updater.log (relocate via symlink)
└── updater-XYZ (relocate via symlink)

Why are the users not located in a subdirectory?
Then you keep the data directory in the local filesystem and relocate just users dir to nfs share:

├── appdata_XYZ 
├── audit.log
├── index.html
├── **users**  (symlink to nfs share)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── user1
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── user2
├── updater.log
└── updater-XYZ 

I hope you know what I mean

**Comment by systemofapwne** [comment]
I stumbled upon the same problem today and I really wish for better separation of real user-data and application data.
Moving user-data in a subfolder might be the most straight forward solution IMHO.
Right now, I am using some bindmount magic in my container, where I actually mount the appdata_/updater-XYZ inside of the whole "userdata" folder, that itself is bindmounted to my SMB shares. That is kind of an ugly but working workaround. So its is far from being an acceptable solution.

Here is an except of my currently working workaround in my docker-compose file. Replace XYZ with your specific instance-id
```
version: '2.4'
services:
  cloud:
    image: nextcloud:latest
    ports:
      - "28080:80/tcp"
    restart: always
    volumes:
      # Storage
      - "/mnt/nextcloud/userdata:/userdata:rw"                        # SMB share
      - "/home/cloud/userdata/appdata_XYZ:/userdata/appdata_XYZ:rw"   # Ugly workaround (Local filesystem)
      - "/home/cloud/userdata/updater-XYZ:/userdata/updater-XYZ:rw"   # Ugly workaround (Local filesystem)
```
