### ISSUE TITLE
[Bug]: Nextcloud + Postgres(15) Docker stack failed to update from 24.0.6 to 25.0.0

### ISSUE THREAD

**Issue by Rollbacke** [nextcloud/server#34817]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

My Nextcloud / Postgres (15) Docker stack failed to update from 24.0.6 version to 25.0.0.
On my docker-compose, I used the latest tag (now, it's forced to 24.0.6 :D).

My `docker-compose.yaml` :
```yaml
---
version: '3.8'

networks:
  net_docker:
    driver: bridge
    ipam:
      driver: default
      config: [{subnet: 10.0.1.0/24, gateway: 10.0.1.1}]

services:
  cloud-psql:
    container_name: cloud-psql
    image: postgres:latest
    env_file:
      - "./cloud-psql/.env"
    volumes:
      - ./cloud-psql/data/:/var/lib/postgresql/data/:rw
    networks:
      net_docker:
        ipv4_address: 10.0.1.2
    restart: unless-stopped

  cloud-redis:
    container_name: cloud-redis
    image: redis:latest
    volumes:
      - ./cloud-redis/data:/data:rw
    networks:
      net_docker:
        ipv4_address: 10.0.1.3
    restart: unless-stopped

  cloud:
    container_name: cloud
    build:
      context: './cloud'
    env_file:
      - "./cloud/.env"
    dns:
      - 10.0.1.15
    volumes:
      - ./cloud/data/nextcloud/:/var/www/html/:rw
      - ./cloud/data/apps/:/var/www/html/custom_apps/:rw
      - ./cloud/data/config/:/var/www/html/config/:rw
      - ./cloud/data/data/:/var/www/html/data/:rw
      - ./cloud/data/themes/:/var/www/html/themes/:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - cloud-psql
      - cloud-redis
    labels:
      [...traefik_labels...]
    networks:
      net_docker_manager:
        ipv4_address: 10.0.1.4
    restart: unless-stopped
```

My postgres `.env` file:
```
POSTGRES_USER=cloud
POSTGRES_PASSWORD=**psqlpassword**
POSTGRES_DB=cloud
```

My Nextcloud `.env` file:
```
POSTGRES_DB=cloud
POSTGRES_USER=cloud
POSTGRES_PASSWORD=**psqlpassword**
POSTGRES_HOST=cloud-psql
NEXTCLOUD_ADMIN_USER=cloudadmin
NEXTCLOUD_ADMIN_PASSWORD=**adminpassword**
NEXTCLOUD_TRUSTED_DOMAINS="cloud.myfqdn.com cloud 10.0.1.4"
REDIS_HOST=cloud-redis
[...some_smtp_mail_var...]
PHP_MEMORY_LIMIT=1024M
PHP_UPLOAD_LIMIT=1024M
APACHE_DISABLE_REWRITE_IP=1
TRUSTED_PROXIES="10.0.1.10/32"
```

My Nextcloud `Dockerfile` file:
```Dockerfile
FROM nextcloud:apache

MAINTAINER Me <me@myfqdn.com>

RUN apt-get update \
  && apt-get install -yq --no-install-suggests --no-install-recommends sudo libmagickcore-6.q16-6-extra \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists

COPY conf/opcache-recommended.ini /usr/local/etc/php/conf.d/opcache-recommended.ini

COPY conf/remoteip.conf /etc/apache2/conf-enabled/remoteip.conf

COPY conf/apache2.conf /etc/apache2/apache2.conf
```

And when I do a pull/up, this is what happens:

From my nextcloud container:
```
cloud        | Initializing nextcloud 25.0.0.18 ...
cloud        | Upgrading nextcloud from 24.0.6.1 ...
cloud        | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
cloud        | You may use your browser or the occ upgrade command to do the upgrade
cloud        | Setting log level to debug
cloud        | Turned on maintenance mode
cloud        | Updating database schema
cloud        | Exception: Database error when running migration 25000Date20220602190540 for app core
cloud        | An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
cloud        | Update failed
cloud        | Maintenance mode is kept active
```

From my postgres container:
```
cloud-psql   | 2022-10-21 20:28:51.148 UTC [37] ERROR:  permission denied for schema public
cloud-psql   | 2022-10-21 20:28:51.148 UTC [37] STATEMENT:  CREATE INDEX expire_date ON oc_comments (expire_date)
```

I already tried to set rights (maybe the wrong way) and change the owner to `cloud`.
My database:
```psql
# psql -U cloud -d cloud
psql (15.0 (Debian 15.0-1.pgdg110+1))
Type "help" for help.

cloud=# \dt
                      List of relations
 Schema |            Name             | Type  |     Owner     
--------+-----------------------------+-------+---------------
 public | oc_accounts                 | table | oc_cloudadmin
 public | oc_accounts_data            | table | oc_cloudadmin
 public | oc_activity                 | table | oc_cloudadmin
 public | oc_activity_mq              | table | oc_cloudadmin
[...]

cloud=# \dn+
                                       List of schemas
  Name  |       Owner       |           Access privileges            |      Description       
--------+-------------------+----------------------------------------+------------------------
 public | pg_database_owner | pg_database_owner=UC/pg_database_owner+| standard public schema
        |                   | =U/pg_database_owner                   | 
(1 row)
```

### Steps to reproduce

1. make a nextcloud/postgres (15) stack from 24.0.6 version
2. change to tag latest or 25.0.0
3. pull, up and see the logs

### Expected behavior

May everything be fine :D

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.bellemainp.fr",
            "cloud",
            "10.0.1.29"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.6.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR",
        "mail_smtpsecure": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit: 1.14.0
  - circles: 24.0.0
  - dashboard: 7.4.0
  - encryption
  - federation: 1.14.0
  - files_external
  - survey_client: 1.12.0
  - text: 3.5.1
  - user_ldap
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Too big.
```

### Additional info

Run on a raspberry pi 4B 8G, on a SSD, on Debian 11 Docker host.
