### ISSUE TITLE
[Bug]: php occ files_external:notify not working

### ISSUE THREAD

**Issue by tigerblue77** [nextcloud/server#36838]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm running the latest [official Nextcloud Docker image](https://hub.docker.com/_/nextcloud) (Nextcloud Hub 3 - 25.0.3) and encounter the following error while running `php occ files_external:notify` command :

![image](https://user-images.githubusercontent.com/37409593/220990231-eba2b70c-7aa1-4eff-a20d-ae9728c84e3f.png)

I need it to use the [files_inotify extension](https://apps.nextcloud.com/apps/files_inotify)

### Steps to reproduce

1. Run docker image. Here is my docker-compose.yaml file (with Jinja2 variables as I deploy it with Ansible) :
```yaml
version: "3.7"

services:
  database:
    container_name: {{ Nextcloud_PostgreSQL_Docker_service_name }}
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: {{ Nextcloud_PostgreSQL_database_name }}
      POSTGRES_USER: {{ Nextcloud_database_user_name }}
      POSTGRES_PASSWORD: {{ Nextcloud_database_password }}
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready", "-U", "{{ Nextcloud_database_user_name }}", "-d", "{{ Nextcloud_PostgreSQL_database_name }}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 4
    #   start_period: 60s
    # logging:
    #   driver: "none"
    volumes:
      - "{{ Nextcloud_PostgreSQL_Docker_volume_name }}:/var/lib/postgresql/data:rw"
    networks:
      - {{ Nextcloud_PostgreSQL_Docker_network_name }}
      # - PostgreSQL_PGadmin
  
  # pgadmin:
  #   # container_name: pgadmin
  #   image: dpage/pgadmin4
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   depends_on:
  #     - postgresql
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: {{ PGadmin_email }}
  #     PGADMIN_DEFAULT_PASSWORD: {{ PGadmin_password }}
  #   volumes:
  #      - PGadmin_data:/var/lib/pgadmin4/storage
  #   ports:
  #     - "82:80"
  #   networks:
  #     - PostgreSQL_PGadmin

  application:
    container_name: {{ Nextcloud_Docker_service_name }}
    image: nextcloud
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - database
      # Not working while it's in the spec : https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1
      # - database:
      #     condition: service_healthy
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: {{ Nextcloud_PostgreSQL_database_name }}
      POSTGRES_USER: {{ Nextcloud_database_user_name }}
      POSTGRES_PASSWORD: {{ Nextcloud_database_password }}
      NEXTCLOUD_ADMIN_USER: {{ Nextcloud_administrator_username }}
      NEXTCLOUD_ADMIN_PASSWORD: {{ Nextcloud_administrator_password }}
      NEXTCLOUD_TRUSTED_DOMAINS: {{ Nextcloud_trusted_domains }} # Optional, space-separated list of domains/IPs
      # TODO : configurer le serveur SMTP lorsqu'il sera créé
      # source : https://github.com/docker-library/docs/blob/master/nextcloud/README.md
      # SMTP_HOST (not set by default): The hostname of the SMTP server.
      # SMTP_SECURE (empty by default): Set to ssl to use SSL, or tls to use STARTTLS.
      # SMTP_PORT (default: 465 for SSL and 25 for non-secure connections): Optional port for the SMTP connection. Use 587 for an alternative port for STARTTLS.
      # SMTP_AUTHTYPE (default: LOGIN): The method used for authentication. Use PLAIN if no authentication is required.
      # SMTP_NAME (empty by default): The username for the authentication.
      # SMTP_PASSWORD (empty by default): The password for the authentication.
      # MAIL_FROM_ADDRESS (not set by default): Use this address for the 'from' field in the emails sent by Nextcloud.
      # MAIL_DOMAIN
      PHP_MEMORY_LIMIT: {{ Nextcloud_memory_limit }} # Default: 512M
      PHP_UPLOAD_LIMIT: {{ Nextcloud_upload_file_size_limit }} # Default: 512M
      # TODO : when Traefik will be configured : https://github.com/docker-library/docs/blob/master/nextcloud/README.md#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
    volumes:
      - "{{ Nextcloud_Docker_volume_name }}:/var/www/html:rw"
    ports:
      - "{{ Nextcloud_Docker_container_port_to_expose }}:80"
    networks:
      - {{ Nextcloud_PostgreSQL_Docker_network_name }}

volumes:
  {{ Nextcloud_PostgreSQL_Docker_volume_name }}:
  {{ Nextcloud_Docker_volume_name }}:
  # PGadmin_data:

networks:
  {{ Nextcloud_PostgreSQL_Docker_network_name }}:
  # PostgreSQL_PGadmin:
```
2. Run `php occ files_external:notify` command

### Expected behavior

Should enable "external files notifications"

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "domain.com",
            "192.168.1.XXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.1.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - files_inotify
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```
