### ISSUE TITLE
[Bug]: Installing with Portainer in Docker Swarm mode with a Stack has installation problem due to oc_admin6 insufficient permissions.

### ISSUE THREAD

**Issue by as-shura** [nextcloud/server#38193]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Based on this docker-compose yaml file the permissions created by the install wizard for the oc_admin6 are insufficient. The installer breaks at some point while filling the Postgres DB.

### Steps to reproduce

In Portainer with Docker swarm mode use this yaml stack. Note that the db container was created in a separate stack. We use only one DB stack shared by many services pointing to the same Postgres DB.

```
version: '3.2'
services:
  nextcloud:
    image: nextcloud
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.hostname == node2
    ports:
      - 9090:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - database-postgres-net

  cron:
    image: nextcloud
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.hostname == node2
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    networks:
      - database-postgres-net
      
networks:
  database-postgres-net:
    external: true

volumes:
  nextcloud:
  ```

### Expected behavior

Perfect first installation process achieved successfully.

### Installation method

Community Docker image

### Nextcloud Server version

24

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
nothing
```

### List of activated Apps

```shell
nothing
```

### Nextcloud Signing status

```shell
nothing
```

### Nextcloud Logs

```shell
nothing
```

### Additional info

nothing
