### ISSUE TITLE
[Bug]: Could not find resource files_external/js/public_key.js to load

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#42158]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Seeing the below errors  under NC 28 RC4  looks similar to https://github.com/nextcloud/server/pull/41766

Could not find resource files_external/js/public_key.js to load
Could not find resource files_external/js/oauth2.js to load
Could not find resource files_external/js/oauth1.js to load

### Steps to reproduce

Not sure

### Expected behavior

No error

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
{"reqId":"KgqH2auQuzMzGRXKdMsw","level":3,"time":"2023-12-11T08:42:01-06:00","remoteAddr":"10.1.1.1","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/externalstorages","message":"Could not find resource files_external/js/public_key.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"28.0.0.10","data":{"app":"jsresourceloader"},"id":"657722ad0cd52"}

{"reqId":"KgqH2auQuzMzGRXKdMsw","level":3,"time":"2023-12-11T08:42:01-06:00","remoteAddr":"10.1.1.1","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/externalstorages","message":"Could not find resource files_external/js/oauth2.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"28.0.0.10","data":{"app":"jsresourceloader"},"id":"657722ad0cd67"}

{"reqId":"KgqH2auQuzMzGRXKdMsw","level":3,"time":"2023-12-11T08:42:01-06:00","remoteAddr":"10.1.1.1","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/externalstorages","message":"Could not find resource files_external/js/oauth1.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"28.0.0.10","data":{"app":"jsresourceloader"},"id":"657722ad0cd7a"}
```

**Comment by Caligatio** [comment]
I'm also affected and it's causing a non-trivial number of "ERROR" level log messages to pile up.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/42428

**Comment by BoBBer446** [comment]
Im Using Docker Compose and get the same.

Compose file:
```yml
version: '3.8'

services:
  nextcloud:
    image: custom-nextcloud:latest
    volumes:
      - /home/docker-projects/nextcloud-fotos:/mnt/Fotos-Nextcloud
      - /home/docker-projects/nextcloud:/var/www/html
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=securepassword
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 192.168.178.36
      - NEXTCLOUD_ADMIN_USER=myuser
      - NEXTCLOUD_ADMIN_PASSWORD=myuser_password
      - NEXTCLOUD_DEFAULT_PHONE_REGION=DE
    ports:
      - "8811:80"
    hostname: nextcloud-server
    container_name: nextcloud-server
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=securepassword
    hostname: nextcloud-db
    container_name: nextcloud-db
    volumes:
      - /home/docker-projects/nextcloud/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    hostname: nextcloud-redis
    container_name: nextcloud-redis
```

Dockerfile
```bash
FROM nextcloud:latest

RUN apt-get update && \
    apt-get install -y libbz2-dev nano ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install bz2
```

Version
[Nextcloud Hub 7](https://nextcloud.com/) (28.0.1)

Current install: Today, 05.01.2024
