### ISSUE TITLE
[Bug]: There are some warnings regarding your setup (v29)

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#44114]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

TEST Uprade from NC 28.0.3 to 29.0.0. BETA: 

There are some warnings regarding your setup.
Could not check that the data directory is protected. Please check manually that your server does not allow access to the data directory. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.
Your webserver is not set up to serve `.js.map` files. Without these files, JavaScript Source Maps won't function properly, making it more challenging to troubleshoot and debug any issues that may arise.
Could not check for JavaScript support. Please check manually if your webserver serves `.mjs` files using the JavaScript MIME type. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.
Could not check if your web server properly resolves the OCM and OCS provider URLs. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.
Could not check that your web server serves `.well-known` correctly. Please check manually. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`. For more details see the [documentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-setup-well-known-URL).
Could not check for WOFF2 loading support. Please check manually if your webserver serves `.woff2` files. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`. For more details see the [documentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-nginx).
Please double check the [installation guides ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-install), and check for any errors or warnings in the [log](https://www.swiss7cloudtest.ch/settings/admin/logging).

### Steps to reproduce

1. run GUI "OVERVIEW

### Expected behavior

no warnings or errors

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```shell
no errors has been found
```

**Comment by rchaconmolero** [comment]
We also have the same problem after updating to Nextcloud Hub 8 version (29.0.0 beta 1) from version 28.0.3. The same messages after update vía GUI web interface.

**Comment by Githopp192** [comment]
Well done :-)

![image](https://github.com/nextcloud/server/assets/32612067/d2496214-de78-4925-b0e1-a357f417f66a)


Security & setup warnings
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

All checks passed.
Check the security of your Nextcloud over [our security scan ↗](https://scan.nextcloud.com/).

Version
[Nextcloud Hub 8](https://nextcloud.com/) (29.0.0 beta 2)

Update
Your version is up to date.

**Comment by Githopp192** [comment]
btw - what did you do with 29.x - it runs much faster than ever - wough - what a difference !

**Comment by joshtrichards** [comment]
Thanks for the report @Githopp192. Going to close this out since it seems fixed. :)

**Comment by rubo77** [comment]
> Therefor it must be able to resolve and connect to at least **one its** ...

should be 

> ... one **of** it's ...

**Comment by rubo77** [comment]
I still have this issue, after updating to NC 29.0.0 yesterday:

```
Could not check that the data directory is protected. Please check manually that your server does not allow access to the data directory. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.
    Your webserver is not set up to serve `.js.map` files. Without these files, JavaScript Source Maps won't function properly, making it more challenging to troubleshoot and debug any issues that may arise.
    Could not check for JavaScript support via any of your `trusted_domains` nor `overwrite.cli.url`. This may be the result of a server-side DNS mismatch or outbound firewall rule. Please check manually if your webserver serves `.mjs` files using the JavaScript MIME type. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.
    Could not check if your web server properly resolves the OCM and OCS provider URLs. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.

    Could not check that your web server is properly set up to allow file synchronization over WebDAV. Please check manually. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`. Weitere Informationen findest du in der [Dokumentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-setup-well-known-URL).
    Could not check that your web server serves `.well-known` correctly. Please check manually. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`. Weitere Informationen findest du in der [Dokumentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-setup-well-known-URL).
    Could not check for WOFF2 loading support. Please check manually if your webserver serves `.woff2` files. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`. Weitere Informationen findest du in der [Dokumentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-nginx).
    
```

I am running NC in a docker-container with this docker-compose:

```

version: '3'

services:
  db:
    image: mariadb
    #?command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb_read_only_compressed=OFF
    restart: "no"
    volumes:
      - /var/kunden/docker-services/next.example.de/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_PASSWORD=***
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    #?env_file:
    #?  - db.env

  redis:
    image: redis:alpine
    restart: always

  # https://github.com/nextcloud/docker/blob/master/14.0/apache/Dockerfile
  #
  app:
    image: nextcloud:29.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:80
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - /nextcloud/next.example.de/html:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
```

maybe, because I linked the volume to another partition?

    - /nextcloud/next.example.de/html:/var/www/html

mountpoint 

    /dev/xvda3 on /nextcloud type ext4 (rw,relatime)


I tried

    chown www-data:www-data /nextcloud/next.example.de -Rf

but the messages are still there
