### ISSUE TITLE
[Bug]: Upgrade from 30.0.0 to 30.0.1 failed

### ISSUE THREAD

**Issue by dlmw** [nextcloud/server#48907]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm using Docker. I updated the image from nextcloud:30.0.0-apache to nextcloud:30.0.1-apache and the server is stuck in maintenance mode when I go to the web page.

When I run `docker container exec -u 33 -it [NEXTCLOUD_CONTAINER_ID] /bin/bash` to try and run `php occ upgrade` manually, here's the error I get:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
LINE 1: CREATE TABLE oc_appconfig_ex (id BIGSERIAL NOT NULL, appid V...
                     ^
Update failed
Maintenance mode is kept active
Resetting log level
```

### Steps to reproduce

1. Get a Nextcloud instance to version 30.0.0
2. Change the image tag to 30.0.1 and rerun with the same volumes
3. Upgrade fails

### Expected behavior

Upgrade should go smoothly

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> `Insufficient privilege: 7 ERROR:  permission denied for schema public`

This is a matter with your configuration, not a bug.

The configured `dbuser` doesn't have privileges to run `CREATE TABLE` apparently. Please troubleshoot via the typical channels - e.g. the help forum: https://help.nextcloud.com 

You can review the permissions required in the Admin Manual - https://help.nextcloud.com

**Comment by dlmw** [comment]
I've run all the setup/migrations with the same user and it always worked fine. This is a matter of configuration, sure; one shared by all the Docker users of Nextcloud.

```yml
nextcloud:
  image: nextcloud:30.0.1-apache
  deploy:
    placement:
      constraints:
        - "node.labels.nextcloud==true"
  volumes:
    - nextcloud-data:/var/www/html
  depends_on:
    - nextcloud-db
  networks:
    - nextcloud-network
    - reverse-proxy-network
  environment:
    - OVERWRITEPROTOCOL=https

nextcloud-db:
  image: postgres:16.4-alpine
  deploy:
    placement:
      constraints:
        - "node.labels.nextcloud-db==true"
  environment:
    - POSTGRES_DB=nextcloud
    - POSTGRES_USER=nextcloud
    - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
  volumes:
    - nextcloud-db:/var/lib/postgresql/data
  networks:
    - nextcloud-network
  secrets:
    - nextcloud_db_password
```
