### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/server#50742]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi is there a reason why my SMB shares never connect when installing NC. Everytime I update the container, I have to manually install smbclient inside the container. Shouldnt that come automatically?

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:11.0
    restart: always
  #  command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --innodb-buffer-pool-size=3G
    volumes:
      - $NCdbdir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=

  app:
    image: nextcloud:30.0.5
     restart: always
    ports:
      - 8585:80
      - 449:443
    links:
      - db
    volumes:
      - /NC26/NC_app:/var/www/html
      - /LIVE180:/var/www/html/data/nmax/live
    
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_HOST=
      - PHP_MEMORY_LIMIT=4048M
      - opcache.enable=1
      - opcache.memory_consumption=1024
      - opcache.save_comments = 1
      - opcache.interned_strings_buffer=64
      - opcache.max_accelerated_files=100000
      - opcache.revalidate_freq=60
      - opcache.jit = 1255
      - opcache.jit_buffer_size = 128M
      - PHP_UPLOAD_LIMIT=2G
#      - REDIS_HOST=redis
#      - PHP__MAX_INPUT_TIME=3600
#      - PHP_MAX_EXECUTION_TIME=3600
#      - NEXTCLOUD_MEMORY_LIMIT=1024M
#      - NEXTCLOUD_UPLOAD_LIMIT=10G 
  cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
    - app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - NEXTCLOUD_CONTAINER_NAME=nc26-app-1
    - NEXTCLOUD_PROJECT_NAME=
    - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
  redis:
    image: redis:alpine
    depends_on:
    - app
    ports: 
    - 6379:6379
    container_name: redis
    privileged: true
    volumes:
      - $Redisdir:/data
        restart: unless-stopped
    
    ```

### Steps to reproduce

1. upgrade container
2. start
3. no SMB connections

### Expected behavior

SMB connections after container upgrase

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```
