### ISSUE TITLE
[Enhancement] Custom DNS configuration for internal HTTP client (IClientService) - Strict-Transport-Security header warning

### ISSUE THREAD

**Issue by adripo** [nextcloud/server#51572]
When running Nextcloud via Docker (using [nextcloud/docker](https://github.com/nextcloud/docker)) behind a reverse proxy like Traefik, which is configured to set HTTP security headers such as `Strict-Transport-Security`, an issue arises during internal security checks.

## **Context:**

- **Deployment Setup:**  
  I'm running Nextcloud in a Docker container with Traefik acting as the reverse proxy. Traefik applies all the necessary HTTP security settings, including HSTS, and these headers are present on external requests (as verified using `curl` and browser requests).

- **Problem Encountered:**  
  The Nextcloud admin overview displays a warning:  
  > `Some headers are not set correctly on your instance - The 'Strict-Transport-Security' HTTP header is not set (should be at least '15552000' seconds). For enhanced security, it is recommended to enable HSTS. For more details see the documentation ↗.`  

  Investigation revealed that this occurs because the security check uses Nextcloud's internal HTTP client service (located at [lib/public/Http/Client](https://github.com/nextcloud/server/tree/master/lib/public/Http/Client)).  
  The security check, particularly in [SecurityHeaders.php](https://github.com/nextcloud/server/blob/9f95c5f209fe3942dd83c68f8a40ccb00ae41413/apps/settings/lib/SetupChecks/SecurityHeaders.php#L101), issues a request to the Nextcloud endpoint `/heartbeat`. However, due to **Docker’s internal DNS resolution**, the domain resolves to an internal container address rather than the external one where Traefik applies its headers.

- **Impact:**  
  As a result, the health check does not see the HSTS header (or any other headers applied by Traefik), leading to a false-positive warning in the admin interface, even though external requests are properly secured.

**Additional Note on Docker DNS Configuration:**  
  Even if a custom DNS is specified in the Docker Compose file or via the `docker run` command, it is ignored by because the Traefik network is configured and will always default to `127.0.0.11`. This is because Docker manages inter-container communication using its internal DNS system when a non-default network is configured, making it impossible to override for these requests.
Ref: https://forums.docker.com/t/dns-settings-ignored/138184/14

## **Feature Request:**

It would be beneficial to allow a custom DNS configuration for HTTP requests made by the IClientService. This would enable specifying an external DNS resolver for these internal requests, ensuring that the correct (external) IP address is used and the corresponding security headers from Traefik are present.

## **Related Issues:**

- https://github.com/nextcloud/server/issues/45184#issuecomment-2094917275
- https://github.com/nextcloud/docker/issues/2348

## **Steps to Reproduce:**

1. Deploy Nextcloud using the official Docker (nextcloud:XX-apache) image behind Traefik.
2. Configure Traefik to set security headers (e.g., HSTS with at least `15552000` seconds).
3. Verify externally (via browser or `curl`) that the headers are correctly set.
4. Observe that the internal HTTP client request (used by the security header check) resolves via Docker's internal DNS, bypassing Traefik, resulting in missing headers and a false warning in the Nextcloud admin overview.

**Comment by joshtrichards** [comment]
Please provide the Nextcloud config and your Compose file that results in this scenario.

Also, please review [Critical changes: Setup checks](https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_28.html#setup-checks).

> However, due to Docker’s internal DNS resolution, the domain resolves to an internal container address rather than the external one where Traefik applies its headers.

Do you have your external URL resolving to a different IP address internally intentionally? That's unclear from your report. The specifics depend on the rest of your Nextcloud configuration. For example, your `overwrite*` values (as noted in the link above).

**Comment by susnux** [comment]
I also operate multiple Nextcloud server using docker containers, this issue only happens if you have some issues with the DNS. E.g. `cloud.example.com` should always be resolved to the external IP not the local IP (this sounds like there is a custom DNS server running?).

(external IP means at least the IP of your proxy)

**Comment by adripo** [comment]
Hi @joshtrichards, @susnux,

Thank you for your feedback.
This is the complete configuration for my deployment:

**Traefik (`compose.yaml`):**

<details>
<summary>compose.yaml</summary>

```yaml
name: traefik

services:
  app:
    image: traefik:v3.3
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy-traefik
      # Http config
      - --entrypoints.web.address=:80
      # Https config
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-traefik
    restart: unless-stopped

networks:
  proxy-traefik:
    name: proxy-traefik
```

</details>

**Nextcloud (`compose.yaml` with `.env`):**

<details>
<summary>compose.yaml</summary>

```yaml
name: ${SERVICE_NAME}

services:
  db:
    image: postgres:${DB_IMAGE_VERSION}
    environment:
      # DB settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud:${APP_IMAGE_VERSION}
    hostname: ${SERVICE_HOSTNAME} # Fix for Apache to reliably determine the server's FQDN
    environment:
     # App settings
     - POSTGRES_HOST=db
     - REDIS_HOST=redis
     # Reverse proxy settings
     - TRUSTED_PROXIES=${APP_TRUSTED_PROXIES}
     - OVERWRITEPROTOCOL=https
     - OVERWRITEHOST=${SERVICE_HOSTNAME}
     - OVERWRITECLIURL=${OVERWRITEPROTOCOL}://${SERVICE_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_HOSTNAME}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure 
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_PORT}
    volumes:
      - nextcloud:/var/www/html
    networks:
      - default
      - proxy-traefik
    restart: unless-stopped
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:${APP_IMAGE_VERSION}
    entrypoint: /cron.sh
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:

networks:
  proxy-traefik:
    external: true
```

</details>

<details>
<summary>.env</summary>

```dotenv
# Service
SERVICE_NAME=nextcloud
APP_IMAGE_VERSION=30-apache
DB_IMAGE_VERSION=16-alpine
SERVICE_PORT=80
SERVICE_HOSTNAME=nextcloud.example.com

# App Settings
NEXTCLOUD_TRUSTED_DOMAINS=${SERVICE_HOSTNAME}

# Reverse proxy
APP_TRUSTED_PROXIES=172.17.0.0/24 # Docker subnet

# DB Settings
POSTGRES_DB=nextcloud
POSTGRES_USER=nextcloud
POSTGRES_PASSWORD=password
```

</details>

---

**Explanation of the Setup:**

- **Proxy docker network (proxy-traefik):**  
   The Traefik container is deployed on a dedicated network called `proxy-traefik`. In my configuration, this network is defined with its own subnet (for example, `172.17.1.0/24`). This is configured with `--providers.docker.network` parameter and allows Traefik to route requests correctly based on the domain rules defined in its labels.

- **Hostname configuration:**  
   In the Nextcloud compose file, I set `hostname: ${SERVICE_HOSTNAME}`. This ensures that Apache inside the Nextcloud container recognizes the container's domain as `nextcloud.example.com`. This, however, will set the Nextcloud domain inside Docker’s internal DNS system (running on `127.0.0.11`) to resolve `nextcloud.example.com` with the internal IP of the container, within the `proxy-traefik` network. For example, Traefik might be at `172.17.1.2` while Nextcloud is at `172.17.1.3`.

- **DNS resolution:**  
   Because Docker manages inter-container DNS resolution automatically, even if I configure custom DNS entries in the compose files, they are ignored in this setup. As a result, when Nextcloud’s internal HTTP client (used in `SecurityHeaders.php`) performs a request towards `nextcloud.example.com`, it resolves to the container's internal IP (`172.17.1.3`) rather than routing through Traefik. This means the request bypasses Traefik and does not include the HSTS and other headers that Traefik sets on external requests.

- **External vs. internal IPs:**  
   While externally, the domain `nextcloud.example.com` correctly routes to Traefik (which applies all the necessary headers), internally, due to the Docker DNS resolution, it points directly to the Nextcloud container. This discrepancy is what triggers the false-positive warning about missing `Strict-Transport-Security` headers in the Nextcloud admin interface.

I hope this better clarifies the issue I am encountering. Let me know if you need further details. Thanks!
