### ISSUE TITLE
CSRF Check Failed when accessing /index.php/settings/users/users?offset=0&limit=50&gid=&pattern=

### ISSUE THREAD

**Issue by jtcressy** [nextcloud/server#5974]
<!--
Thanks for reporting issues back to Nextcloud! This is the issue tracker of Nextcloud, if you have any support question please check out https://nextcloud.com/support

This is the bug tracker for the Server component. Find other components at https://github.com/nextcloud/

For reporting potential security issues please see https://nextcloud.com/security/

To make it possible for us to help you please fill out below information carefully. 
You can also use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
--> 
### Steps to reproduce
1. Enable and Configure LDAP (LDAP users can login)
2. As an admin, attempt to list users at /index.php/settings/users
3. Spinning icon goes forever and never lists users
4. Disable LDAP app
5. List users again, works immediately.
### Expected behaviour
User list appears and shows both local and LDAP users

### Actual behaviour
XHR request for ``/index.php/settings/users/users?offset=0&limit=50&gid=&pattern=`` fails with 504 error, after multiple attempts the response is 200 with content containing an error message 
```
Access forbidden
CSRF check failed
```
Logs show this entry when ``"loglevel" => 0``:
```
{"reqId":"n9yt4ucQ4bNWkgOhoQlT","level":0,"time":"2017-08-03T21:59:17+00:00","remoteAddr":"10.128.0.1","user":"admin","app":"no app in context","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=50&gid=&pattern=","message":"CSRF check failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.115 Safari\/537.36","version":"12.0.0.29"}
```

### Server configuration

**Operating system**: 
Docker Container (Debian based)
**Web server:**
Apache 2.4.10 (Debian)
**Database:**
MariaDB 10.1.19 (runs separately from this docker container)
**PHP version:**
7.1.7
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
No, fresh install.
**Where did you install Nextcloud from:**
Docker: https://hub.docker.com/_/nextcloud/
Using tag ``latest`` (same as 12-apache)
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                                                                                                                                                                                                                                             
  - activity: 2.5.2                                                                                                                                                                                                                                  
  - admin_audit: 1.2.0                                                                                                                                                                                                                               
  - bruteforcesettings: 1.0.2                                                                                                                                                                                                                        
  - calendar: 1.5.3                                                                                                                                                                                                                                  
  - checksum: 0.3.5                                                                                                                                                                                                                                  
  - comments: 1.2.0                                                                                                                                                                                                                                  
  - dav: 1.3.0                                                                                                                                                                                                                                       
  - deck: 0.2.1                                                                                                                                                                                                                                      
  - external: 2.0.3                                                                                                                                                                                                                                  
  - federatedfilesharing: 1.2.0                                                                                                                                                                                                                      
  - federation: 1.2.0                                                                                                                                                                                                                                
  - files: 1.7.2                                                                                                                                                                                                                                     
  - files_external: 1.3.0                                                                                                                                                                                                                            
  - files_markdown: 1.0.1                                                                                                                                                                                                                            
  - files_pdfviewer: 1.1.1                                                                                                                                                                                                                           
  - files_reader: 1.0.4                                                                                                                                                                                                                              
  - files_texteditor: 2.4.1                                                                                                                                                                                                                          
  - files_trashbin: 1.2.0                                                                                                                                                                                                                            
  - files_versions: 1.5.0                                                                                                                                                                                                                            
  - files_videoplayer: 1.1.0                                                                                                                                                                                                                         
  - firstrunwizard: 2.1                                                                                                                                                                                                                              
  - gallery: 17.0.0                                                                                                                                                                                                                                  
  - logreader: 2.0.0                                                                                                                                                                                                                                 
  - lookup_server_connector: 1.0.0                                                                                                                                                                                                                   
  - mail: 0.6.4                                                                                                                                                                                                                                      
  - nextcloud_announcements: 1.1                                                                                                                                                                                                                     
  - notes: 2.3.1                                                                                                                                                                                                                                     
  - notifications: 2.0.0                                                                                                                                                                                                                             
  - oauth2: 1.0.5                                                                                                                                                                                                                                    
  - password_policy: 1.2.2                                                                                                                                                                                                                           
  - provisioning_api: 1.2.0                                                                                                                                                                                                                          
  - serverinfo: 1.2.0                                                                                                                                                                                                                                
  - sharebymail: 1.2.0                                                                                                                                                                                                                               
  - survey_client: 1.0.0                                                                                                                                                                                                                             
  - systemtags: 1.2.0                                                                                                                                                                                                                                
  - tasks: 0.9.5                                                                                                                                                                                                                                     
  - theming: 1.3.0                                                                                                                                                                                                                                   
  - twofactor_backupcodes: 1.1.1                                                                                                                                                                                                                     
  - updatenotification: 1.2.0                                                                                                                                                                                                                        
  - user_external: 0.4                                                                                                                                                                                                                               
  - user_ldap: 1.2.1                                                                                                                                                                                                                                 
  - workflowengine: 1.2.0                                                                                                                                                                                                                            
Disabled:                                                                                                                                                                                                                                            
  - encryption                                                                                                                                                                                                                                       
  - files_sharing
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{                                                                                                                                                                                                                                                    
    "system": {                                                                                                                                                                                                                                      
        "memcache.local": "\\OC\\Memcache\\APCu",                                                                                                                                                                                                    
        "apps_paths": [                                                                                                                                                                                                                              
            {                                                                                                                                                                                                                                        
                "path": "\/var\/www\/html\/apps",                                                                                                                                                                                                    
                "url": "\/apps",                                                                                                                                                                                                                     
                "writable": false                                                                                                                                                                                                                    
            },                                                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                        
                "path": "\/var\/www\/html\/custom_apps",                                                                                                                                                                                             
                "url": "\/custom_apps",                                                                                                                                                                                                              
                "writable": true                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                                        
        ],                                                                                                                                                                                                                                           
        "instanceid": "oc6b26w8pic6",                                                                                                                                                                                                                
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                             
        "secret": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                   
        "trusted_domains": [                                                                                                                                                                                                                         
            "nextcloud.jtcressy.net"                                                                                                                                                                                                                 
        ],                                                                                                                                                                                                                                           
        "loglevel": 0,                                                                                                                                                                                                                               
        "datadirectory": "\/var\/www\/html\/data",                                                                                                                                                                                                   
        "overwrite.cli.url": "https:\/\/nextcloud.jtcressy.net",                                                                                                                                                                                     
        "dbtype": "mysql",                                                                                                                                                                                                                           
        "version": "12.0.0.29",                                                                                                                                                                                                                      
        "dbname": "nextcloud",                                                                                                                                                                                                                       
        "dbhost": "main-mariadb",                                                                                                                                                                                                                    
        "dbport": "",                                                                                                                                                                                                                                
        "dbtableprefix": "oc_",                                                                                                                                                                                                                      
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                   
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                               
        "installed": true,                                                                                                                                                                                                                           
        "mail_from_address": "noreply",                                                                                                                                                                                                              
        "mail_smtpmode": "php",                                                                                                                                                                                                                      
        "mail_smtpauthtype": "LOGIN",                                                                                                                                                                                                                
        "mail_domain": "jtcressy.net",                                                                                                                                                                                                               
        "ldapIgnoreNamingRules": false,                                                                                                                                                                                                              
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"                                                                                                                                                                               
    }                                                                                                                                                                                                                                                
}   
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, Google Drive and sftp
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP/ActiveDirectory
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
| ldapAttributesForGroupSearch  |                                                                                                                                            |                                                                       
| ldapAttributesForUserSearch   | %sAMAccountName                                                                                                                            |                                                                       
| ldapBackupHost                |                                                                                                                                            |                                                                       
| ldapBackupPort                |                                                                                                                                            |                                                                       
| ldapBase                      | DC=home,DC=jtcressy,DC=net                                                                                                                 |                                                                       
| ldapBaseGroups                | dc=home,dc=jtcressy,dc=net                                                                                                                 |                                                                       
| ldapBaseUsers                 | dc=home,dc=jtcressy,dc=net                                                                                                                 |                                                                       
| ldapCacheTTL                  | 600                                                                                                                                        |                                                                       
| ldapConfigurationActive       | 1                                                                                                                                          |                                                                       
| ldapDefaultPPolicyDN          |                                                                                                                                            |                                                                       
| ldapDynamicGroupMemberURL     |                                                                                                                                            |                                                                       
| ldapEmailAttribute            |                                                                                                                                            |                                                                       
| ldapExperiencedAdmin          | 0                                                                                                                                          |                                                                       
| ldapExpertUUIDGroupAttr       |                                                                                                                                            |                                                                       
| ldapExpertUUIDUserAttr        |                                                                                                                                            |                                                                       
| ldapExpertUsernameAttr        |                                                                                                                                            |                                                                       
| ldapGidNumber                 | gidNumber                                                                                                                                  |                                                                       
| ldapGroupDisplayName          | cn                                                                                                                                         |                                                                       
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=Users)(cn=Domain Users)(cn=Domain Admins)))                                                                  |                                                                       
| ldapGroupFilterGroups         | Users;Domain Users;Domain Admins                                                                                                           |                                                                       
| ldapGroupFilterMode           | 0                                                                                                                                          |                                                                       
| ldapGroupFilterObjectclass    | group                                                                                                                                      |                                                                       
| ldapGroupMemberAssocAttr      | member                                                                                                                                     |                                                                       
| ldapHost                      | home-iis.jtcressy-net.endpoints.cluster.local                                                                                              |                                                                       
| ldapIgnoreNamingRules         |                                                                                                                                            |                                                                       
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Domain Users,CN=Users,DC=home,DC=jtcressy,DC=net)(primaryGroupID=513))))(samaccountname=%uid)) |                                                                       
| ldapLoginFilterAttributes     |                                                                                                                                            |                                                                       
| ldapLoginFilterEmail          | 0                                                                                                                                          |                                                                       
| ldapLoginFilterMode           | 1                                                                                                                                          |                                                                       
| ldapLoginFilterUsername       | 1                                                                                                                                          |                                                                       
| ldapNestedGroups              | 0                                                                                                                                          |                                                                       
| ldapOverrideMainServer        |                                                                                                                                            |                                                                       
| ldapPagingSize                | 500                                                                                                                                        |                                                                       
| ldapPort                      | 389                                                                                                                                        |                                                                       
| ldapQuotaAttribute            |                                                                                                                                            |                                                                       
| ldapQuotaDefault              |                                                                                                                                            |                                                                       
| ldapTLS                       | 0                                                                                                                                          |                                                                       
| ldapUserDisplayName           | displayName                                                                                                                                |                                                                       
| ldapUserDisplayName2          | email                                                                                                                                      |                                                                       
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Domain Users,CN=Users,DC=home,DC=jtcressy,DC=net)(primaryGroupID=513))))                         |                                                                       
| ldapUserFilterGroups          | Domain Users                                                                                                                               |                                                                       
| ldapUserFilterMode            | 0                                                                                                                                          |                                                                       
| ldapUserFilterObjectclass     | person                                                                                                                                     |                                                                       
| ldapUuidGroupAttribute        | auto                                                                                                                                       |                                                                       
| ldapUuidUserAttribute         | auto                                                                                                                                       |                                                                       
| turnOffCertCheck              | 0                                                                                                                                          |                                                                       
| turnOnPasswordChange          | 1                                                                                                                                          |                                                                       
| useMemberOfToDetectMembership | 1                                                                                                                                          |                                                                       
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Log too long to insert, relevant entry above under actual behavior
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:7 JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2246 Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
hide @ merged-template-prepend.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2246
initDeleteHandling @ users.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:343
(anonymous) @ users.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:682
j @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
fireWith @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
ready @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
I @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
merged-template-prepend.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2246 Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
hide @ merged-template-prepend.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2246
initDeleteHandling @ groups.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:289
(anonymous) @ groups.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:336
j @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
fireWith @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
ready @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
I @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:4 GET https://nextcloud.jtcressy.net/index.php/settings/users/users?offset=0&limit=50&gid=&pattern= 504 (Gateway Time-out)
send @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:4
ajax @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:4
n.(anonymous function) @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:4
update @ users.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:383
(anonymous) @ users.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:1152
j @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
fireWith @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
ready @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
I @ core.js?v=3e8fbb6e56d0cc4982a523cd35d6e68d-24:2
```
```
Network log too long
```
</details>
