### ISSUE TITLE
(Postgres) User does not have CONNECT privilege. 

### ISSUE THREAD

**Issue by tateisu** [nextcloud/server#8915]
### Steps to reproduce

when trying '13-apache' docker image with database container 'postgres:9.6-alpine'.
I was experienced error on setup form.

```
Error while trying to create admin user: 
Failed to connect to the database: An exception occured in driver: 
SQLSTATE[08006] [7] FATAL: permission denied for database "postgres" 
DETAIL: User does not have CONNECT privilege. 
```

form parameters:
admin name: tateisu_admin
admin password: (randomly generated password)
data folder: /var/www/html/data
database type] postgres
db user: postgres
db password: (pre-defined password for postgres database user )
db name: postgres
db host: db (same as service name in docker-compose.yml )

then checking detabase user, app creates role for admin user for each I try setup.

```
postgres=# \du
                                       List of roles
     Role name     |                         Attributes                         | Member of 
-------------------+------------------------------------------------------------+-----------
 oc_tateisu_admin  | Create DB                                                  | {}
 oc_tateisu_admin2 | Create DB                                                  | {}
 oc_tateisu_admin3 | Create DB                                                  | {}
 oc_tateisu_admin4 | Create DB                                                  | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

How to avoid this error? 

### Expected behaviour
- complete setup page.

### Actual behaviour
- setup form raises error.

### Server configuration

my docker-compose.yml is here.
```
version: '2'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - ../postgres:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud:13-apache
    restart: always
    ports:
      - "172.17.0.1:8003:80"
    volumes:  
      - /etc/localtime:/etc/localtime:ro
      - ../data:/var/www/html
    depends_on:
      - db
```

**Operating system**:
Ubuntu 16.04.2 LTS x64

**Web server:**
nginx

**Database:**
 'postgres:9.6-alpine' container

**PHP version:**
**Nextcloud version:** (see Nextcloud admin page)
official docker container '13-apache'

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
