### ISSUE TITLE
Nextcloud docker doesn't sync files reliably from Mac: internal server error

### ISSUE THREAD

**Issue by vephinx** [nextcloud/server#9624]
### Steps to reproduce
1. Install nextcloud via https://github.com/evertramos/docker-nextcloud-letsencrypt with the https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
2. Install the Nextcloud App for Mac
3. Add files to the Nextcloud folder to sync

### Expected behaviour
I expect my files to sync without a problem. 

### Actual behaviour
The Nextcloud app syncs some files and then it stops. It gives an error in syncing: `server replied: Internal Server Error`.
What is strange is that I can access my files no problem via the web interface, and that it will sync a few items before crashing. 

When the crash occurs, `...php_network_getaddresses: getaddrinfo failed...` appears in the docker log as below.

### Server configuration

**Operating system**:
Ubuntu 16.04

Running latest: 
https://github.com/evertramos/docker-nextcloud-letsencrypt
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

My `docker-compose.yml`:

```
version: '3'

services:
  cloud-app:
    depends_on:
      - cloud-db
    container_name: ${APP_CONTAINER_NAME}
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - "3005:80"
    volumes:
      - ${LOCAL_DATA_DIR}:/var/www/html
      - ${LOCAL_CONF_DIR}:/var/www/html/config
      - ${LOCAL_APPS_DIR}:/var/www/html/apps
    environment:
      # NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      # NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
      NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: "3005"
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}

  cloud-db:
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3308:3306"
    volumes:
      - ${LOCAL_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
    default:
       external:
         name: ${NETWORK}
```

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bookmarks
  - comments
  - deck
  - encryption
  - files_external
  - files_pdfviewer
  - notes
  - systemtags
  - tasks
  - theming
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** volumes configured by `docker-compose.yml`.

**Are you using encryption:** letsencrypt, no file encryption

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox 60.0.1 (64-bit)

**Operating system:**
Mac 10.12.6

#### Web server error log

Web server error log

[php7:error] [pid 27] [client 80.60.217.8:40102] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\D in /var/www/html/lib/private/DB/Connection.php on line 64

#### Nextcloud log

Browser log

<img width="968" alt="screen shot 2018-05-27 at 17 53 23" src="https://user-images.githubusercontent.com/2012398/40587996-3d2c9646-61d7-11e8-867f-c368c67500a3.png">
